### ISSUE TITLE
Input objects lose parent-child relationship

### ISSUE THREAD

**Issue by denisvmedyantsev** [insight-platform/Savant#104]
Information about the parent object is lost when adding objects from the input meta. For example, if there are a person and a face on the input of a module, where the parent of the face is the person, now we will get two unrelated objects on the module output. 

We have to set properly a parent object for every incoming object and add a test for this functionality.

**Comment by abramov-oleg** [comment]
Working on this issue revealed a related bug:

Object's parent property assigned through Savant meta in a pyfunc is not saved:

- the parent is not assigned in the meta json results
- the parent is still assigned to primary object (`frame`) even in the same pyfunc in when a new iterator is created for a ```for obj_meta in frame_meta.objects``` loop
