### ISSUE TITLE
Optional EOS for file-based sources

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#115]
When file-based adapters are used, they must support mandatory passing EOS or ignore it. It is necessary to support making it possible to use trackers in processing pipelines that use tracking, and source-adapter feeds the framework on a file-by-file basis infinitely.

**Comment by denisvmedyantsev** [comment]
We have `EOS_ON_LOCATION_CHANGE` parameter in the media files source adapter, but currently set it automatically, depending on the adapter type (image or video). We can allow users to set it.
https://github.com/insight-platform/Savant/blob/develop/adapters/gst/sources/media_files.sh#L31
