### ISSUE TITLE
Frame loss with a specific video file in "Source > Module" bundle

### ISSUE THREAD

**Issue by denisvmedyantsev** [insight-platform/Savant#120]
There is frame loss with the current Dealer-Router configuration for Source-Module. 

There is no loss if set 1) sync=1 for the source (decrease FPS significantly) or 2) modify HWM (requires investigation, see https://github.com/zeromq/jeromq/issues/703) or 3) change ZMQ schema to REQ-REP.

To reproduce run `./scripts/run_source.py videos --source-id=0 ../vlf-pipelines/data/bottle_defect_detector/test.mp4` and module with minimal config, and compare log messages `Processed N frame..` for source and module (2494 vs 2478 in my case, 16 frames loss).

module config
```
name: test
parameters:
  batch_size: 1
```

**Comment by denisvmedyantsev** [comment]
It also relates to our internal tests
* avc_hevc_to_single_json
* avc_hevc_to_single_json_all_sources
* avc_hevc_to_single_json_filter_source
* avc_hevc_to_single_json_filter_source_prefix

**Comment by bwsw** [comment]
@tomskikh please ask Denis for details.

**Comment by tomskikh** [comment]
@denisvmedyantsev We can fix this by setting HWM to 0 for ROUTER socket or by implementing confirmation that module processed all messages. The source sends special message and waits for the reply before closing the socket. This approach looks more reliable and don't need to turn off HWM. But we need to ensure ROUTER socket doesn't drop messages before DEALER socket is closed.

**Comment by denisvmedyantsev** [comment]
> The source sends special message and waits for the reply before closing the socket. 

Can't we use EOS for this?

**Comment by tomskikh** [comment]
> Can't we use EOS for this?

No. `zeromq_sink` cannot distinguish EOS and frame messages since they are serialized in `video_to_avro_serializer`.
