### ISSUE TITLE
Create a script which will quickly check if the environment is compatible with the framework version

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#122]
Script must check 0.2.0 release compatibilty.

Place it to: `utils/check-environment-compatible`.

To check:
- docker engine
- nvidia-container-runtime
- driver version (if x86 dGPU)
- Jetpack version (if jetson/arm)

When everything is OK, the script must return exit code `0` and `echo Environment is OK`; in case of error, `exit 1` and `echo Environment is not configured properly`.

Use `cat / etc / nv_tegra_release` to find if it is Jetson and check the Jetpack version.

Use 
https://stackoverflow.com/questions/13125714/how-to-get-the-nvidia-driver-version-from-the-command-line
to check the driver version on the PC.

Use:
```
docker run --gpus=all ubuntu bash
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container: context canceled 
```
to check that GPUs are available and Nvidia container runtime is configured.

That is it.

**Comment by bwsw** [comment]
Use `cat / etc / nv_tegra_release` to find if it is Jetson and check Jetpack version.

Use 
https://stackoverflow.com/questions/13125714/how-to-get-the-nvidia-driver-version-from-the-command-line
to check the driver version on PC.

Use:
```
docker run --gpus=all ubuntu bash
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container: context canceled 
```
to check that GPUs are available and nvidia container runtime is configured.

That is it.

**Comment by denisvmedyantsev** [comment]
You can use `dpkg-query --show nvidia-l4t-core` to get more detailed JetPack version information, see an example on https://github.com/insight-platform/Savant/blob/2da5362982599f0058bce4aaf19fa0bcb8d9710f/savant/utils/platform.py#L10
