### ISSUE TITLE
Fix check environment script

### ISSUE THREAD

**Issue by denisvmedyantsev** [insight-platform/Savant#127]
Find a way to check if docker supports GPU without docker run.

https://github.com/insight-platform/Savant/blob/3fcc44aa317777265384a96a14f2e9f6d9bbd40b/utils/check-environment-compatible#L4

Eg. we can try to check nvidia-container-toolkit `dpkg-query --show nvidia-container-toolkit`

**Comment by abramov-oleg** [comment]
One option to improve this was to use al lightweight Docker image instead of `ubuntu` and remove it after the check.

I've tested images `alpine`, `bash`, `busybox` or `hello-world`, and 

```
docker run -it --gpus all <image>
``` 

fail with these images on Jetson, with the message

```
docker: Error response from daemon: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #1: error running hook: exit status 1, stdout: , stderr: time="2023-04-04T16:22:25+07:00" level=error msg="failed to update ld.so.conf: failed to create config file: open /var/lib/docker/overlay2/686cc7f0ef1c3f73b63f5e8a6ac29bc7c142b936194ec6a6dc54da584ad0884c/merged/etc/ld.so.conf.d/nvcr-687693471.conf: no such file or directory": unknown.
```

**Comment by bwsw** [comment]
@abramov-oleg we may leave the current one if it works, just add the removal command to the script.
