### ISSUE TITLE
Document how to setup the development environment

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#146]
We need a tutorial and dev environment on how to develop for Savant. It looks like the simplest way to develop for Savant is to use "Remote Environment", which can be found in IntelliJ Professional tools. 
They allow execution of the source code within the docker container created from a certain image.

1. The user downloads the container;
2. She uses the container as a remote environment;
3. The PyCharm introspects it and extracts all the libraries and they become available in the IDE (Savant must be installed as EGG);
4. The user creates YAML pipeline in a project root;
5. The user creates pyfuncs;
6. The user specifies "main.py" where she specifies YAML to load, iterator to get [(frame, meta), ...] and class to receive results.
7. On "run", the pipeline is launched and works until the iterator yields the data.
8. The logs are displayed in the Run console.
9. The HowTo explains how to pack the project to Savant.

It enables the creation of test suites and interactive development.

Pseudocode:

```python
pipeline = Pipeline("config.yml")
       .process(source="name", fps=1/30, src_iterator1, sink_cls_instance2)
       .process(source="other-name", fps=-1, src_iterator2, sink_cls_instance2)
       .run(parallel=True) # blocking
```

* Pipeline,
* Element (image[, extra_meta: MetaObject]) - in, out
* EOS
* OpenCVMat | JPEGBuffer
* MetaObject

I tried to use Remote Docker Runtime in PyCharm Professional, it works for local Docker daemon well, but doesn't work well for remote SSH-accessed Docker.

![image](https://user-images.githubusercontent.com/15047882/230781070-48a828d2-83dc-4260-8761-8f54e65b6307.png)

![image](https://user-images.githubusercontent.com/15047882/230781105-f02dc2f4-5cca-4a55-9d8c-128756946cf7.png)

![image](https://user-images.githubusercontent.com/15047882/230781157-0bf168ff-2d7f-4fbf-b1f9-279f00d0e72a.png)

![image](https://user-images.githubusercontent.com/15047882/230781202-3e8c31fb-a385-4281-aa70-d4e5ead52ce2.png)

How to craft #147

**Comment by bwsw** [comment]
Implement as part of #160

**Comment by denisvmedyantsev** [comment]
To run savant with docker interpreter in pycharm do not forget to add `--gpus=all` in docker run options.
![Screenshot from 2023-04-21 12-10-22](https://user-images.githubusercontent.com/44088010/233673340-7665c217-1c69-4477-9051-e498a3d0b5f7.png)
