### ISSUE TITLE
The discord invite link is broken

### ISSUE THREAD

**Issue by ajaykrishnan33** [insight-platform/Savant#168]
<img width="762" alt="Screenshot 2023-04-15 at 5 08 16 PM" src="https://user-images.githubusercontent.com/8767512/232214759-0d080f39-b524-450a-8564-079c274c6692.png">

**Comment by bwsw** [comment]
@ajaykrishnan33 thank you. I will take a look soon.

**Comment by bwsw** [comment]
@ajaykrishnan33 the link if fixed, thank you!
The actual link is: https://discord.com/invite/KVAfGBsZGd
