### ISSUE TITLE
Keep the original frame resolution/aspect ratio on pipeline output

### ISSUE THREAD

**Issue by tomskikh** [insight-platform/Savant#20]
Scale frames to the original resolution & aspect ratio before sending them to the pipeline output (should be configurable).

**Comment by denisvmedyantsev** [comment]
I propose to consider a new [nvstreammux](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvstreammux2.html) and process frames in their original size.

**Comment by tomskikh** [comment]
> I propose to consider a new [nvstreammux](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvstreammux2.html) and process frames in their original size.

A new nvstreammux isn't ready yet for the Savant. Caps on the source pad of `nvstreammux` and `nvstreamdemux` are the caps of the first connected source, i.e. the caps are not valid. Hence we need to use `nvviceoconvert` before `nvstreammux` to ensure all frames have the same resolution and color format. So, there is no point for us to use the new `nvstreammux` now.
