### ISSUE TITLE
Compare YOLOv8 Savant vs PyTorch

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#206]
Make the performance comparison demo which includes the following phases:
* decoding video ([cuda-accelerated](https://pytorch.org/audio/main/hw_acceleration_tutorial.html#Benchmark-NVDEC-with-StreamReader));
* encoding video ([cuda-accelerated](https://pytorch.org/audio/main/hw_acceleration_tutorial.html#Benchmark-NVENC-with-StreamWriter));
* inference + postprocessing

**Comment by abramov-oleg** [comment]
Implementation here https://github.com/insight-platform/SavantPyTorchComparison/pull/1
