### ISSUE TITLE
Bounding Boxes are displayed incorrectly in overlay 

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#273]
![image](https://github.com/insight-platform/Savant/assets/15047882/a00d8601-9e9e-449d-9d98-6a88631b53dc)

Please, check if it is:

1. a savant-rs bug
2. a draw_func bug

Pipeline to test: https://github.com/insight-platform/Savant/tree/269-two-rtsp/samples/multiple_rtsp

**Comment by abramov-oleg** [comment]
This is an encoding artifact that manifests for bounding boxes with border thickness set to 1.

To fix, `savant-rs` version is updated; new version sets default box border thickness to 2.
