### ISSUE TITLE
Sink adapter doesn't display video and pictures

### ISSUE THREAD

**Issue by smirnova-oi** [insight-platform/Savant#28]
**Run commands**:  

1. `LOGLEVEL=DEBUG ./scripts/run_module.py samples/deepstream_test2/module.yml`
2. `./scripts/run_sink.py display`
3. `./scripts/run_source.py pictures black_bottles.jpg --source-id src-id-1`

**Result**:  sink adapter failing with error:
```
Traceback (most recent call last):
  File "/opt/app/adapters/ds/gst_plugins/python/avro_video_player.py", line 174, in _add_branch
    assert pad.link(branch.sink.get_static_pad('sink')) == Gst.PadLinkReturn.OK
  File "/usr/lib/python3/dist-packages/gi/overrides/Gst.py", line 178, in link
    raise LinkError(ret)
gi.overrides.Gst.LinkError: <enum GST_PAD_LINK_NOFORMAT of type Gst.PadLinkReturn>
Traceback (most recent call last):
  File "/opt/app/savant/gstreamer/utils.py", line 112, in on_pad_event
    return event_handler(pad, event, *data)
  File "/opt/app/savant/gst_plugins/python/avro_video_decode_bin.py", line 337, in on_src_pad_eos
    peer.send_event(Gst.Event.new_eos())
AttributeError: 'NoneType' object has no attribute 'send_event'
```

[black_bottles.tar.gz](https://github.com/insight-platform/Savant/files/9978727/black_bottles.tar.gz)

**Notes**: 

- This problem is relevant for any type of source adapter. 
- Combination `source_adapter-module`  works  because another type of sink adapter gives correct result (image, video and json file are written aright).  Display sink param only error.

**Comment by tomskikh** [comment]
Display-sink works for `output_frame.codec=raw-rgba` if capsfilters before autovideosink are removed (https://github.com/insight-platform/Savant/pull/34/commits/1ae70f84ee71e028fa1c86ce1b78b657e2ac661f). But to make it working for any other `output_frame.codec` I'll change logic of adding/removing sources - similar to the one in `NvDsPipeline`.

**Comment by tomskikh** [comment]
> Display-sink works for `output_frame.codec=raw-rgba` if capsfilters before autovideosink are removed ([1ae70f8](https://github.com/insight-platform/Savant/commit/1ae70f84ee71e028fa1c86ce1b78b657e2ac661f)). But to make it working for any other `output_frame.codec` I'll change logic of adding/removing sources - similar to the one in `NvDsPipeline`.

`nveglglessink` fails with "cuda init error" when sink pad has caps `video/x-raw(memory:NVMM)`. Added capsfilter `video/x-raw`.

**Comment by smirnova-oi** [comment]
Tested. Sink works with all codec types.
