### ISSUE TITLE
Support Similari trackers for objects [SORT]

### ISSUE THREAD

**Issue by denisvmedyantsev** [insight-platform/Savant#29]
Add the ability to use [Similari](https://github.com/insight-platform/Similari) trackers in Savant pipelines (only sort for now). 

Similari is now available on the PyPI repository:

```
pip install similari-trackers-rs==0.26.1
```

**Comment by bwsw** [comment]
It must be a separate standalone ready-to-use element for SORT trackers based on Similari SORT. The tracker must support IoU or Maha measure, oriented and axis-aligned boxes, and other properties of Similari. 

The tracker must utilize Similari Batch API and support multi-class tracking with the following scene construction approach: `(class_id << 16) + map[source_id > int]`.
