### ISSUE TITLE
Handle correct termination when a 0mq REQ socket reaches timeout

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#311]
When a socket reaches timeout, the module must be terminated correctly, not with the exception. Use a proper termination code like `1` for the exit function. Use a proper message like `Error: The REP socket hasn't responded in a configured timeframe (xxxx) ms. Exit (1).`

![image](https://github.com/insight-platform/Savant/assets/15047882/eb0da13c-ca21-4b36-9753-efa63f7b000f)

**Comment by tomskikh** [comment]
@bwsw How to reproduce this issue?
