### ISSUE TITLE
Image upscale/sr demo

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#317]
Convert 640x480 to FHD

**Comment by denisvmedyantsev** [comment]
Use lightweight models [NinaSR](https://github.com/Coloquinte/torchSR/blob/main/doc/NinaSR.md) 
 (ninasr_b0 0.10M, ninasr_b1 1.02M params) from [TorchSR repo](https://github.com/Coloquinte/torchSR).

Input video H264 360p, output H265 resolution x2=720p / x3=1080p / x4=1440p

RTX 3070 Laptop:
| Model  | Scale | Inference only, FPS | Inference + Replace, FPS | Demo, FPS |
| ------------- | --- | ----- | ---- | ---- |
| ninasr_b0 | 2  | 141 | 84 | 106(?) |
| ninasr_b0 | 3  | 135 | 52 | 49 |
| ninasr_b0 | 4  | 126 | 26 | 25 |
| ninasr_b1 | 2  |  28 |  26 | |
| ninasr_b1 | 3  |  31 |  29 | |
| ninasr_b1 | 4  |  26 |  22 | |

Xavier NX:
| Model  | Scale | Inference only, FPS | Inference + Replace, FPS | Demo, FPS |
| ------------- | --- | ----- | ---- | ---- |
| ninasr_b0 | 2  | 18 | 13 | 12 |

Where "Replace" is a pyfunc that places the result (super resolution) on top of the original frame, increasing the original frame size (360p) with paddings. This is different from a demonstration where we show the original (upscaled) and the result at the same time.

Running the demo on Xavier NX results in lots of `WARN savant_rs::message::validate_seq_iq`, Always-on-sink displays broken video.

**Comment by denisvmedyantsev** [comment]
[examples](https://drive.google.com/drive/folders/1H8eibzHzzn6Vy6EqK3Pl7MzBtFkvGU8k?usp=sharing)
