### ISSUE TITLE
Compatibility check script and compose-s fail on Jetson

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#320]
Script

```
check-environment-compatible
```

fails running on freshly deployed Jetson hardware. It also concerns all our compose files related to Jetson.

The problem already met twice. We either need a guide to update freshly deployed Jetsons or fix the files to conform default software.

Compose:
![unnamed](https://github.com/insight-platform/Savant/assets/15047882/92812375-c460-4eec-af02-4670cd7bff10)

- Red: works on newer Jetson software
- Green: doesn't work

**Comment by bwsw** [comment]
Check on Jetson with Docker:
Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.2

**Comment by denisvmedyantsev** [comment]
Checked on Jetson NX with Docker version 24.0.5 and Jetson AGX with Docker version 20.10.25. Both require `--runtime=nvidia` and do not support `--gpus=all`.
