### ISSUE TITLE
Programmatic Source/Sink Framework

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#342]
We need a framework for development and QA purposes to establish Pythonic API, allowing a user to inject (frame_meta, frame_image) into the pipeline and receive the resulting stream back to the framework.

From user's perspective, the framework can work as a simple map-like iterator: the user establishes the input seq and the timeout and can iterate over results. It can even run infinitely if the input seq is also an iterator.

The framework would be used for developing purposes and QA. It must be developed based on the OpenCV instruments. Frames are sent in the module, and the module configures the encoding format for the resulting objects.

The framework interacts with the module via standard ZeroMQ sockets: they can be configured during the framework initialization; by default, they must be compatible with the module's defaults.

The framework lives inside the module's Docker image (Savant wheel) and allows running test cases with standalone scripts or the "pytest" or "unittest" packages.

# Mandatory Dependencies

* Savant RS

# High-level Objects

* Runtime;
* Source;
* Sink;
* LogProvider (JaegerLogProvider);
* Source (JPEGSource);

# API

API design is demonstrational, don't need to be implemented literally.

## Write/Read

```python

results = map(
   Runtime
     .with_timeout(ms)
     .with_sockets(source, sink)
     .with_log_provider(JaegerLogProvider("http://localhost:16686/api/traces", login_opt, password_opt)
     .build(), [JPEGSource(stream_id, filename).with_update(VideoFrameUpdate(...)), JPEGSource(...)]

for r in results:
   r.frame_data
   r.frame_meta
   r.logs.pp()
```

## Write Only (Source)

```python

results = map(
   Source
     .with_timeout(ms)
     .with_socket(socket)
     .with_log_provider(JaegerLogProvider("http://localhost:16686/api/traces", login_opt, password_opt)
     .build(), [JPEGSource(stream_id, filename).with_update(VideoFrameUpdate(...)), JPEGSource(...)]

for r in results:
   r.status
   r.logs.pp()
```

## Read Only (Sink)

```python

results = 
   Sink
     .with_socket(socket)
     .with_log_provider(JaegerLogProvider("http://localhost:16686/api/traces", login_opt, password_opt)
     .build()

for r in results:
   r.frame_data
   r.frame_meta
   r.logs.pp()
```

# HowTo Use It

* without development in Docker: framework must be available as wheel extractable from Savant Image to install in a host system (Savant wheel);
* with development in Docker.

# How To Fetch Logs

Logs are accessible from the tracing system (by default, the tracing system can be omitted).

The new savant-rs logging allows injecting logs into traces: we only need to use proper logging, generate traces in the Source, and format logs beautifully on the client side.

If the tracing system is not used, logs can be observed in the Docker console where the Savant module is run.

# How To Match the Input to the Output

There are two approaches:
* with trace_id;
* with custom attribute injected into frame meta.

**Comment by tomskikh** [comment]
Source, Sink, JpegSource implemented so far.

# Source example

```python
import logging

from savant_rs.primitives import Attribute, AttributeValue, VideoFrameUpdate

from savant.source_sink_framework import JpegSource, SourceBuilder
from savant.utils.logging import init_logging

logger = logging.getLogger('source-test')

init_logging('DEBUG')

jpeg_source = JpegSource('cam-1', 'data/AVG-TownCentre.jpeg')
jpeg_sources = []
for i in range(5):
    update = VideoFrameUpdate()
    update.add_attribute(
        Attribute(namespace='foo', name='bar', values=[AttributeValue.integer(i)])
    )
    jpeg_sources.append(
        jpeg_source.with_update(update).with_pts(jpeg_source.duration * i)
    )

source = (
    SourceBuilder()
    .with_timeout(1.0)
    .with_socket('req+connect:ipc:///tmp/zmq-sockets/input-video.ipc')
    .build()
)

# send single frame
result = source(jpeg_source)
logger.info('result: %s', result)

# send multiple frames
result = source.send_iter(jpeg_sources)
for r in result:
    logger.info('result: %s', r)
```

# Sink example

```python
import logging

from savant.source_sink_framework import SinkBuilder
from savant.utils.logging import init_logging

logger = logging.getLogger('source-test')

init_logging('DEBUG')

sink = (
    SinkBuilder()
    .with_socket('rep+connect:ipc:///tmp/zmq-sockets/output-video.ipc')
    .build()
)

for r in sink:
    if r.frame_meta is not None:
        logger.info(
            'frame meta: %s',
            (r.frame_meta.source_id, r.frame_meta.pts, r.frame_meta.transformations),
        )
        for attr_ns, attr_name in r.frame_meta.attributes:
            logger.info('attribute: %s', r.frame_meta.get_attribute(attr_ns, attr_name))
    else:
        logger.info('result: %s', r)
```
