### ISSUE TITLE
HW Accelerated JPEG encoder for X86 and DS 6.3

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#347]
According to the changelog, DS 6.3 introduced an HW-accelerated JPEG encoder.

**Comment by bwsw** [comment]
CHECK:

- HW JPEGDEC (JETSON) CHECK 
- ENC IDR FRAMES

**Comment by denisvmedyantsev** [comment]
NVidia changed docker container set - https://catalog.ngc.nvidia.com/orgs/nvidia/collections/deepstream_sdk. We have to double-check our builds. It might be better to build a completely custom docker image based on GStreamer and DS SDK, including only what we need.

**Comment by denisvmedyantsev** [comment]
The [bug with jpeg decoding via nvv4l2decoder on Jetson](https://github.com/insight-platform/Savant/issues/314) is still relevant for DS 6.3 (checked with nvcr.io/nvidia/deepstream-l4t:6.3-samples).

**Comment by denisvmedyantsev** [comment]
DS 6.3 fixed the [bug with no IDR frames after nvv4l2h264enc](https://forums.developer.nvidia.com/t/deepstream-6-2version-seems-not-produce-idr-periodically). 
```
gst-launch-1.0 videotestsrc num-buffers=1000 ! nvvideoconvert ! nvv4l2h264enc ! filesink location=test.h264
```
then
```
ffprobe -v error -select_streams v:0 -count_frames -show_entries stream=nb_read_frames -skip_frame nokey test.h264
```
For DS 6.2 gives `nb_read_frames=1`, for DS 6.3 - `nb_read_frames=4`.

DS 6.3 nvv4l2h26Xenc supports `idrinterval` parameter (default=256) in addition to `iframeinterval`  on dGPU (and Jetson).

**Comment by denisvmedyantsev** [comment]
The current Savant code tries to use `nvencoder` first. If the user specified `output_frame: jpeg`, Savant will try to build the encoder using `nvjpegenc` and will only use `jpegenc` if `nvjpegenc` is not available (https://github.com/insight-platform/Savant/pull/44). Thus, there is nothing to do.
