### ISSUE TITLE
Implement multi-stream source test adapter

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#372]
The adapter must create multiple video streams and send them with different source ids like `source-%d`. We can specify the parallelism and number of frames. The adapter is used for performance tests. At the end of the operation, it sends a shutdown if configured (#371).

**Comment by denisvmedyantsev** [comment]
yolov8_seg demo, rtx3070
* run_perf (uridecodebin, bs=1): Processed 1550 frames, 31.69 FPS.
* run_perf (uridecodebin, bs=4): Processed 1550 frames, 31.92 FPS.
* run_perf_multistream (num_streams=1, bs=1): Processed 1550 frames, 29.72 FPS.
* run_perf_multistream (num_streams=1, bs=4): Processed 1550 frames, 31.36 FPS.
* run_perf_multistream (num_streams=2, bs=4): Processed 3100 frames, 51.50 FPS.
* run_perf_multistream (num_streams=4, bs=4): Processed 6200 frames, 86.20 FPS.
