### ISSUE TITLE
Access to frames from PyFunc as OpenCV GpuMat

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#43]
To provide to way to access batch elements as GpuMat OpenCV class.

**Comment by tomskikh** [comment]
Found [this](https://forum.opencv.org/t/use-pre-allocated-cuda-memory-pointer-to-initialize-an-opencv-gpumat-in-python/203/9) discussion on opencv forum. Opencv doesn't have python bindings for `GpuMat (int rows, int cols, int type, void *data, size_t step=Mat::AUTO_STEP)`. I've tried the suggested solution to add a constructor that converts `uint64` to `void *` and modified it a bit.
```
    CV_WRAP inline GpuMat(bool not_used, int rows, int cols, int type, uint64 dataAddr, size_t step = Mat::AUTO_STEP):
        GpuMat(rows, cols, type, (void*)dataAddr, step){}
```
