### ISSUE TITLE
Software encoding working?

### ISSUE THREAD

**Issue by elfar** [insight-platform/Savant#450]
Hi, first of all congrats on great work on this, really impressive setup as well as documentation!

Been playing around with Jetson Orin Nano Developer Kit on e.g. samples 
 - rtsp_cam_compatibility_test
 - peoplenet_detector

with branches "develop" as well as release 0.2.5. As you point out, Orin Nano does not support nvenc. So when I run either sample out of the box it will fail with error regarding exactly that.

always-on-sink_1     |  INFO  insight::savant::deepstream::encoding > Checking if encoder for codec 'h264' is available
always-on-sink_1     |  INFO  insight::savant::gstreamer::runner    > Starting pipeline `<Gst.Pipeline object at 0xffff50367800 (GstPipeline at 0x181aa1c0)>`...
always-on-sink_1     |  INFO  insight::savant::gstreamer::runner    > The pipeline is initialized and ready to process data. Initialization took 0:00:00.001107.
always-on-sink_1     |  ERROR insight::savant::gstreamer::runner    > Received error "gst-resource-error-quark: Cannot identify device '/dev/v4l2-nvenc'. (3)" from nvv4l2h264enc0.
always-on-sink_1     |  INFO  insight::savant::gstreamer::runner    > The pipeline is about to stop. Operation took 0:00:00.001376.
always-on-sink_1     | Exception in thread Thread-1:
always-on-sink_1     | Traceback (most recent call last):
always-on-sink_1     |   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
always-on-sink_1     |     self.run()
always-on-sink_1     |   File "/usr/lib/python3.8/threading.py", line 870, in run
always-on-sink_1     |     self._target(*self._args, **self._kwargs)
always-on-sink_1     |   File "/usr/local/lib/python3.8/dist-packages/savant/gstreamer/runner.py", line 72, in _main_loop_run
always-on-sink_1     |     raise RuntimeError(self._error)
always-on-sink_1     | RuntimeError: Received error "gst-resource-error-quark: Cannot identify device '/dev/v4l2-nvenc'. (3)" from nvv4l2h264enc0. Debug info: "/dvs/git/dirty/git-master_linux/3rdparty/gst/gst-v4l2/gst-v4l2/v4l2_calls.c(637): gst_v4l2_open (): /GstPipeline:pipeline0/nvv4l2h264enc:nvv4l2h264enc0:
always-on-sink_1     | system error: No such file or directory".
always-on-sink_1     |  ERROR insight::savant::deepstream::encoding > You have configured NVENC-accelerated encoding, but your device doesn't support NVENC.
peoplenet_detector_always-on-sink_1 exited with code 0

However, when I change module.yml to

  output_frame:
    # Frame is output without any encoding
    # this is to circumvent 3 hardware decoding processes limit on NVIDIA consumer hardware
    codec: h264
    encoder: software

I still get that same error, was specifying software not supposed to force software encoding or?

Also, as defining "encoder: software" is only, as far as I can see, an option for the "module". How would I go about making "always-on-sink_1" a.k.a. "broadcaster" in "rtsp_cam_compatibility_test" use software encoder?

**Comment by bwsw** [comment]
@elfar hello. The Always-on RTSP sink is a hardware-only RTSP caster. The module can use 'software' encoders, but this sink adapter supports only NVENC.

You can deploy AO-RTSP on a GPU-enabled host and connect the module on Nano over network sockets rather than Unix sockets. You can also implement a custom RTSP casting adapter with Client SDK and OpenCV.

**Comment by elfar** [comment]
@bwsw - Ah, understood, was slowly arriving at this conclusion through the documentation, but great to have it confirmed. Thanks for the quick reply. Much appreciated!
