### ISSUE TITLE
face_reid error in new release

### ISSUE THREAD

**Issue by MyraBaba** [insight-platform/Savant#451]
bc@bc:~/Projects/OpenSource/Savant/samples/face_reid$ docker compose -f docker-compose.x86.yml --profile index up
[+] Running 2/0
 ✔ Container face_reid-index-builder-1    Created                                              0.0s
 ✔ Container face_reid-pictures-source-1  Created                                              0.0s
Attaching to face_reid-index-builder-1, face_reid-pictures-source-1
face_reid-index-builder-1    |  INFO  insight::savant::config::module_config > Configure module...
face_reid-index-builder-1    |  WARN  insight::savant::config::json_resolver > JSON loads fail, returning None for "None".
face_reid-index-builder-1    |  WARN  insight::savant::config::json_resolver > JSON loads fail, returning None for "None".
face_reid-index-builder-1    |  WARN  insight::savant::config::json_resolver > JSON loads fail, returning None for "None".
face_reid-index-builder-1    |  INFO  insight::savant::config::module_config > Configure pipeline elements...
face_reid-index-builder-1    |  INFO  insight::savant::deepstream::nvinfer::element_config > Element nvinfer@complex_model:v1(name=yolov8nface): Path to the model files has been set to "/models/yolov8nface".
face_reid-index-builder-1    |  INFO  insight::savant::remote_file                         > Destination folder "/models/yolov8nface" is empty, remote file will be downloaded.
face_reid-index-builder-1    |  INFO  insight::savant::remote_file                         > Downloading s3://savant-data/models/yolov8face/yolov8nface.md5...
100%|██████████| 50/50 [00:00<00:00, 267.20it/s]
face_reid-index-builder-1    |  INFO  insight::savant::remote_file                         > Downloading s3://savant-data/models/yolov8face/yolov8nface.zip...
100%|██████████| 10796297/10796297 [00:04<00:00, 2405185.75it/s]
face_reid-index-builder-1    |  INFO  insight::savant::remote_file                         > Remote file "/downloads/yolov8nface/yolov8nface.zip" has been downloaded and unpacked. Files ['yolov8n-face.onnx', 'yolov8n-face.txt'] have been placed in "/models/yolov8nface".
face_reid-index-builder-1    |  INFO  insight::savant::deepstream::nvinfer::element_config > Element nvinfer@complex_model:v1(name=yolov8nface): Configuration file "/models/yolov8nface/yolov8n-face.txt" has been loaded. Processing of the model will be done according to the given configuration file.
face_reid-index-builder-1    |  WARN  insight::savant::deepstream::nvinfer::element_config > Element nvinfer@complex_model:v1(name=yolov8nface): Model engine file "/models/yolov8nface/yolov8n-face.onnx_b1_gpu0_fp16.engine" not found.
face_reid-index-builder-1    |  INFO  insight::savant::deepstream::nvinfer::element_config > Element nvinfer@complex_model:v1(name=yolov8nface): Model output converter will be used.
face_reid-index-builder-1    |  INFO  insight::savant::deepstream::nvinfer::element_config > Element nvinfer@complex_model:v1(name=yolov8nface): Resulting configuration file "/models/yolov8nface/yolov8n-face_config_savant.txt" has been saved.
face_reid-index-builder-1    |  INFO  insight::savant::deepstream::nvinfer::element_config > Element nvinfer@attribute_model:v1(name=adaface_ir50_webface4m_90fb74c): Path to the model files has been set to "/models/adaface_ir50_webface4m_90fb74c".
face_reid-index-builder-1    |  INFO  insight::savant::remote_file                         > Destination folder "/models/adaface_ir50_webface4m_90fb74c" is empty, remote file will be downloaded.
face_reid-index-builder-1    |  INFO  insight::savant::remote_file                         > Downloading s3://savant-data/models/adaface_ir50_webface4m_90fb74c/adaface_ir50_webface4m_90fb74c.md5...
100%|██████████| 69/69 [00:00<00:00, 109.57it/s]
face_reid-index-builder-1    |  INFO  insight::savant::remote_file                         > Downloading s3://savant-data/models/adaface_ir50_webface4m_90fb74c/adaface_ir50_webface4m_90fb74c.zip...
100%|██████████| 162478269/162478269 [01:03<00:00, 2547394.11it/s]
face_reid-index-builder-1    |  INFO  insight::savant::remote_file                         > Remote file "/downloads/adaface_ir50_webface4m_90fb74c/adaface_ir50_webface4m_90fb74c.zip" has been downloaded and unpacked. Files ['adaface_ir50_webface4m.onnx'] have been placed in "/models/adaface_ir50_webface4m_90fb74c".
face_reid-index-builder-1    |  INFO  insight::savant::deepstream::nvinfer::element_config > Element nvinfer@attribute_model:v1(name=adaface_ir50_webface4m_90fb74c): Model engine file has been set to "adaface_ir50_webface4m.onnx_b4_gpu0_fp16.engine".
face_reid-index-builder-1    |  INFO  insight::savant::deepstream::nvinfer::element_config > Element nvinfer@attribute_model:v1(name=adaface_ir50_webface4m_90fb74c): Resulting configuration file "/models/adaface_ir50_webface4m_90fb74c/adaface_ir50_webface4m_config_savant.txt" has been saved.
face_reid-index-builder-1    |  INFO  insight::savant::config::module_config               > Pipeline batch size is set to 1.
face_reid-index-builder-1    |  INFO  insight::savant::config::module_config               > Module configuration is complete.
face_reid-index-builder-1    |  INFO  insight::savant::deepstream::utils::pipeline         > No telemetry provider specified. Using noop tracer.
face_reid-index-builder-1    |  INFO  insight::savant::face_reid_index_builder             > Pipeline frame processing parameters: {'width': 1280, 'height': 720, 'batch-size': 1, 'buffer-pool-size': 4, 'batched-push-timeout': 2000, 'live-source': False, 'interpolation-method': 6, 'drop-pipeline-eos': True, 'nvbuf-memory-type': 3}.
face_reid-index-builder-1    | Traceback (most recent call last):
face_reid-index-builder-1    |   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
face_reid-index-builder-1    |     return _run_code(code, main_globals, None,
face_reid-index-builder-1    |   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
face_reid-index-builder-1    |     exec(code, run_globals)
face_reid-index-builder-1    |   File "/usr/local/lib/python3.8/dist-packages/savant/entrypoint/__main__.py", line 11, in <module>
face_reid-index-builder-1    |     main(sys.argv[1])
face_reid-index-builder-1    |   File "/usr/local/lib/python3.8/dist-packages/savant/entrypoint/main.py", line 65, in main
face_reid-index-builder-1    |     pipeline = NvDsPipeline(
face_reid-index-builder-1    |   File "/usr/local/lib/python3.8/dist-packages/savant/deepstream/pipeline.py", line 156, in __init__
face_reid-index-builder-1    |     super().__init__(name, pipeline_cfg, **kwargs)
face_reid-index-builder-1    |   File "/usr/local/lib/python3.8/dist-packages/savant/gstreamer/pipeline.py", line 67, in __init__
face_reid-index-builder-1    |     self.add_element(
face_reid-index-builder-1    |   File "/usr/local/lib/python3.8/dist-packages/savant/deepstream/pipeline.py", line 192, in add_element
face_reid-index-builder-1    |     gst_element = super().add_element(
face_reid-index-builder-1    |   File "/usr/local/lib/python3.8/dist-packages/savant/gstreamer/pipeline.py", line 112, in add_element
face_reid-index-builder-1    |     element.model.output.converter.load_user_code()
face_reid-index-builder-1    |   File "/usr/local/lib/python3.8/dist-packages/savant/base/pyfunc.py", line 174, in load_user_code
face_reid-index-builder-1    |     raise exc
face_reid-index-builder-1    |   File "/usr/local/lib/python3.8/dist-packages/savant/base/pyfunc.py", line 168, in load_user_code
face_reid-index-builder-1    |     spec = pyfunc_module_spec_factory(self)
face_reid-index-builder-1    |   File "/usr/local/lib/python3.8/dist-packages/savant/base/pyfunc.py", line 336, in pyfunc_module_spec_factory
face_reid-index-builder-1    |     if not spec.has_location:
face_reid-index-builder-1    | AttributeError: 'NoneType' object has no attribute 'has_location'
dependency failed to start: container face_reid-index-builder-1 exited (1)

**Comment by bwsw** [comment]
@MyraBaba You need to rebuild Docker images used in compose. I’ve received such an error too. It is because of outdated images.

**Comment by MyraBaba** [comment]
All of them ?


ghcr.io/insight-platform/savant-adapters-deepstream   latest                    e611dc5d4362   2 weeks ago    13.3GB
ghcr.io/insight-platform/savant-deepstream            latest                    503c584187b6   2 weeks ago    13.2GB
ghcr.io/insight-platform/savant-adapters-gstreamer    latest                    b4aeddfc6fb4   2 weeks ago    711MB

**Comment by MyraBaba** [comment]
Any way to rebuilt rather than download all gigs?

**Comment by bwsw** [comment]
@MyraBaba not them. Grep ‘face’ in images or look in the compose. Basic images just need to be pulled if not in sync. 

By the way, release images have 0.2.5 tags. Latest are for develop. Look release tags here: https://github.com/insight-platform/Savant/releases/tag/v0.2.5

And avoid discrepancy, if you want to use release checkout the tag…
