### ISSUE TITLE
test different video for face_reid

### ISSUE THREAD

**Issue by MyraBaba** [insight-platform/Savant#452]
Hi,

I changed the video-loop-source LOCATION to my local video  in /tmp/video-loop-source-downloads ;docker-compose.x86.yml for face_reid

I got below error for mp4 file:

 WARN  insight::savant::gstreamer::runner                   > Received warning gst-library-error-quark: NvInfer output-tensor-meta is enabled but init_params auto increase memory (auto-inc-mem) is disabled. The bufferpool will not be automatically resized. (5). gstnvinfer.cpp(887): gst_nvinfer_start (): /GstPipeline:face_reid/GstNvInfer:yolov8nface
face_reid-video-loop-source-1  | + required_env SOURCE_ID
face_reid-video-loop-source-1  | + [[ -z video ]]
face_reid-video-loop-source-1  | + required_env LOCATION
face_reid-video-loop-source-1  | + [[ -z /tmp/video-loop-source-downloads/facevid_masked.mp4 ]]
face_reid-video-loop-source-1  | + required_env ZMQ_ENDPOINT
face_reid-video-loop-source-1  | + [[ -z pub+connect:ipc:///tmp/zmq-sockets/input-video.ipc ]]
face_reid-video-loop-source-1  | + required_env DOWNLOAD_PATH
face_reid-video-loop-source-1  | + [[ -z /tmp/video-loop-source-downloads ]]
face_reid-video-loop-source-1  | + ZMQ_SOCKET_TYPE=DEALER
face_reid-video-loop-source-1  | + ZMQ_SOCKET_BIND=false
face_reid-video-loop-source-1  | + SYNC_OUTPUT=True
face_reid-video-loop-source-1  | + FPS_OUTPUT=stdout
face_reid-video-loop-source-1  | + [[ -n '' ]]
face_reid-video-loop-source-1  | + [[ -n '' ]]
face_reid-video-loop-source-1  | + FPS_PERIOD=period-frames=1000
face_reid-video-loop-source-1  | + MEASURE_FPS_PER_LOOP=false
face_reid-video-loop-source-1  | + EOS_ON_LOOP_END=false
face_reid-video-loop-source-1  | + READ_METADATA=false
face_reid-video-loop-source-1  | + PIPELINE=(media_files_src_bin location="${LOCATION}" file-type=video loop-file=true download-path="${DOWNLOAD_PATH}" ! fps_meter "${FPS_PERIOD}" output="${FPS_OUTPUT}" measure-per-loop="${MEASURE_FPS_PER_LOOP}" ! adjust_timestamps !)
face_reid-video-loop-source-1  | + [[ -n '' ]]
face_reid-video-loop-source-1  | + PIPELINE+=(savant_rs_serializer source-id="${SOURCE_ID}" eos-on-loop-end="${EOS_ON_LOOP_END}" read-metadata="${READ_METADATA}" ! zeromq_sink socket="${ZMQ_ENDPOINT}" socket-type="${ZMQ_SOCKET_TYPE}" bind="${ZMQ_SOCKET_BIND}" sync="${SYNC_OUTPUT}")
face_reid-video-loop-source-1  | + trap handler SIGINT SIGTERM
face_reid-video-loop-source-1  | + child_pid=7
face_reid-video-loop-source-1  | + wait 7
face_reid-video-loop-source-1  | + gst-launch-1.0 --eos-on-shutdown media_files_src_bin location=/tmp/video-loop-source-downloads/facevid_masked.mp4 file-type=video loop-file=true download-path=/tmp/video-loop-source-downloads '!' fps_meter period-frames=1000 output=stdout measure-per-loop=false '!' adjust_timestamps '!' savant_rs_serializer source-id=video eos-on-loop-end=false read-metadata=false '!' zeromq_sink socket=pub+connect:ipc:///tmp/zmq-sockets/input-video.ipc socket-type=DEALER bind=false sync=True
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:7): GStreamer-CRITICAL **: 18:02:11.201: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:7): GStreamer-CRITICAL **: 18:02:11.202: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:7): GStreamer-CRITICAL **: 18:02:11.202: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:7): GStreamer-CRITICAL **: 18:02:11.202: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:7): GStreamer-CRITICAL **: 18:02:11.202: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  | Setting pipeline to PAUSED ...
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Changing state from <enum GST_STATE_NULL of type Gst.State> to <enum GST_STATE_READY of type Gst.State>
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Reading 1 video files
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Reading file /tmp/video-loop-source-downloads/facevid_masked.mp4
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Changing state from <enum GST_STATE_READY of type Gst.State> to <enum GST_STATE_PAUSED of type Gst.State>
face_reid-video-loop-source-1  | Pipeline is PREROLLING ...
face_reid-video-loop-source-1  | ERROR: from element /GstPipeline:pipeline0/media_files_src_bin+MediaFilesSrcBin:media_files_src_bin+mediafilessrcbin0/GstQTDemux:qtdemux0: Internal data stream error.
face_reid-video-loop-source-1  | Additional debug info:
face_reid-video-loop-source-1  | ../gst/isomp4/qtdemux.c(6749): gst_qtdemux_loop (): /GstPipeline:pipeline0/media_files_src_bin+MediaFilesSrcBin:media_files_src_bin+mediafilessrcbin0/GstQTDemux:qtdemux0:
face_reid-video-loop-source-1  | streaming stopped, reason not-linked (-1)
face_reid-video-loop-source-1  | ERROR: pipeline doesn't want to preroll.
face_reid-video-loop-source-1  | Setting pipeline to NULL ...
face_reid-video-loop-source-1  |  INFO  insight::savant::zeromq_sink::zeromq_sink+zeromqsink0 > Closing ZeroMQ socket
face_reid-video-loop-source-1  |  INFO  insight::savant::zeromq_sink::zeromq_sink+zeromqsink0 > Terminating ZeroMQ context.
face_reid-video-loop-source-1  |  INFO  insight::savant::zeromq_sink::zeromq_sink+zeromqsink0 > ZeroMQ context terminated
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin                  > Changing state from <enum GST_STATE_PAUSED of type Gst.State> to <enum GST_STATE_NULL of type Gst.State>
face_reid-video-loop-source-1  | Freeing pipeline ...
face_reid-video-loop-source-1 exited with code 0
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:8): GStreamer-CRITICAL **: 18:02:12.090: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:8): GStreamer-CRITICAL **: 18:02:12.091: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:8): GStreamer-CRITICAL **: 18:02:12.091: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:8): GStreamer-CRITICAL **: 18:02:12.091: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:8): GStreamer-CRITICAL **: 18:02:12.091: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  | Setting pipeline to PAUSED ...
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Changing state from <enum GST_STATE_NULL of type Gst.State> to <enum GST_STATE_READY of type Gst.State>
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Reading 1 video files
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Reading file /tmp/video-loop-source-downloads/facevid_masked.mp4
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Changing state from <enum GST_STATE_READY of type Gst.State> to <enum GST_STATE_PAUSED of type Gst.State>
face_reid-video-loop-source-1  | Pipeline is PREROLLING ...
face_reid-video-loop-source-1  | ERROR: from element /GstPipeline:pipeline0/media_files_src_bin+MediaFilesSrcBin:media_files_src_bin+mediafilessrcbin0/GstQTDemux:qtdemux0: Internal data stream error.
face_reid-video-loop-source-1  | Additional debug info:
face_reid-video-loop-source-1  | ../gst/isomp4/qtdemux.c(6749): gst_qtdemux_loop (): /GstPipeline:pipeline0/media_files_src_bin+MediaFilesSrcBin:media_files_src_bin+mediafilessrcbin0/GstQTDemux:qtdemux0:
face_reid-video-loop-source-1  | streaming stopped, reason not-linked (-1)
face_reid-video-loop-source-1  | ERROR: pipeline doesn't want to preroll.
face_reid-video-loop-source-1  | Setting pipeline to NULL ...
face_reid-video-loop-source-1  |  INFO  insight::savant::zeromq_sink::zeromq_sink+zeromqsink0 > Closing ZeroMQ socket
face_reid-video-loop-source-1  |  INFO  insight::savant::zeromq_sink::zeromq_sink+zeromqsink0 > Terminating ZeroMQ context.
face_reid-video-loop-source-1  |  INFO  insight::savant::zeromq_sink::zeromq_sink+zeromqsink0 > ZeroMQ context terminated
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin                  > Changing state from <enum GST_STATE_PAUSED of type Gst.State> to <enum GST_STATE_NULL of type Gst.State>
face_reid-video-loop-source-1  | Freeing pipeline ...
face_reid-video-loop-source-1 exited with code 1
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:7): GStreamer-CRITICAL **: 18:02:12.794: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:7): GStreamer-CRITICAL **: 18:02:12.794: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:7): GStreamer-CRITICAL **: 18:02:12.794: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:7): GStreamer-CRITICAL **: 18:02:12.794: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:7): GStreamer-CRITICAL **: 18:02:12.795: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  | Setting pipeline to PAUSED ...
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Changing state from <enum GST_STATE_NULL of type Gst.State> to <enum GST_STATE_READY of type Gst.State>
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Reading 1 video files
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Reading file /tmp/video-loop-source-downloads/facevid_masked.mp4
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Changing state from <enum GST_STATE_READY of type Gst.State> to <enum GST_STATE_PAUSED of type Gst.State>
face_reid-video-loop-source-1  | Pipeline is PREROLLING ...
face_reid-video-loop-source-1  | ERROR: from element /GstPipeline:pipeline0/media_files_src_bin+MediaFilesSrcBin:media_files_src_bin+mediafilessrcbin0/GstQTDemux:qtdemux0: Internal data stream error.
face_reid-video-loop-source-1  | Additional debug info:
face_reid-video-loop-source-1  | ../gst/isomp4/qtdemux.c(6749): gst_qtdemux_loop (): /GstPipeline:pipeline0/media_files_src_bin+MediaFilesSrcBin:media_files_src_bin+mediafilessrcbin0/GstQTDemux:qtdemux0:
face_reid-video-loop-source-1  | streaming stopped, reason not-linked (-1)
face_reid-video-loop-source-1  | ERROR: pipeline doesn't want to preroll.
face_reid-video-loop-source-1  | Setting pipeline to NULL ...
face_reid-video-loop-source-1  |  INFO  insight::savant::zeromq_sink::zeromq_sink+zeromqsink0 > Closing ZeroMQ socket
face_reid-video-loop-source-1  |  INFO  insight::savant::zeromq_sink::zeromq_sink+zeromqsink0 > Terminating ZeroMQ context.
face_reid-video-loop-source-1  |  INFO  insight::savant::zeromq_sink::zeromq_sink+zeromqsink0 > ZeroMQ context terminated
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin                  > Changing state from <enum GST_STATE_PAUSED of type Gst.State> to <enum GST_STATE_NULL of type Gst.State>
face_reid-video-loop-source-1  | Freeing pipeline ...
face_reid-video-loop-source-1 exited with code 1
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:7): GStreamer-CRITICAL **: 18:02:13.676: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:7): GStreamer-CRITICAL **: 18:02:13.676: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:7): GStreamer-CRITICAL **: 18:02:13.676: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:7): GStreamer-CRITICAL **: 18:02:13.676: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  |
face_reid-video-loop-source-1  | (gst-launch-1.0:7): GStreamer-CRITICAL **: 18:02:13.677: The created element should be floating, this is probably caused by faulty bindings
face_reid-video-loop-source-1  | Setting pipeline to PAUSED ...
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Changing state from <enum GST_STATE_NULL of type Gst.State> to <enum GST_STATE_READY of type Gst.State>
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Reading 1 video files
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Reading file /tmp/video-loop-source-downloads/facevid_masked.mp4
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin > Changing state from <enum GST_STATE_READY of type Gst.State> to <enum GST_STATE_PAUSED of type Gst.State>
face_reid-video-loop-source-1  | Pipeline is PREROLLING ...
face_reid-video-loop-source-1  | Setting pipeline to NULL ...
face_reid-video-loop-source-1  | ERROR: from element /GstPipeline:pipeline0/media_files_src_bin+MediaFilesSrcBin:media_files_src_bin+mediafilessrcbin0/GstQTDemux:qtdemux0: Internal data stream error.
face_reid-video-loop-source-1  | Additional debug info:
face_reid-video-loop-source-1  | ../gst/isomp4/qtdemux.c(6749): gst_qtdemux_loop (): /GstPipeline:pipeline0/media_files_src_bin+MediaFilesSrcBin:media_files_src_bin+mediafilessrcbin0/GstQTDemux:qtdemux0:
face_reid-video-loop-source-1  | streaming stopped, reason not-linked (-1)
face_reid-video-loop-source-1  | ERROR: pipeline doesn't want to preroll.
face_reid-video-loop-source-1  |  INFO  insight::savant::zeromq_sink::zeromq_sink+zeromqsink0 > Closing ZeroMQ socket
face_reid-video-loop-source-1  |  INFO  insight::savant::zeromq_sink::zeromq_sink+zeromqsink0 > Terminating ZeroMQ context.
face_reid-video-loop-source-1  |  INFO  insight::savant::zeromq_sink::zeromq_sink+zeromqsink0 > ZeroMQ context terminated
face_reid-video-loop-source-1  |  INFO  insight::savant::media_files_src_bin                  > Changing state from <enum GST_STATE_PAUSED of type Gst.State> to <enum GST_STATE_NULL of type Gst.State>
face_reid-video-loop-source-1  | Freeing pipeline ...

**Comment by bwsw** [comment]
@MyraBaba please share the video so we can reproduce the problem.

**Comment by tomskikh** [comment]
@MyraBaba We need either a video file or debug logs
```
      - LOGLEVEL=debug
      - GST_DEBUG=2
```

**Comment by bwsw** [comment]
@MyraBaba also you can try `:latest`, where we added MKV container support today.

**Comment by MyraBaba** [comment]
@bwsw 

Hi I solved the problem with ffmpeg convert to mp4 so its ok now.

But one particular problem is really annoying. 

person face photo 16:9 restriction and error check if there is no face in the image pass and give a warning.

Such as I want to index all LFW and and a few more face which is appears in the test video so I can see the performance check.


But the LFW faces cant be indexed . This is one of the blocker.

Second I am not sure is it looking for the folder and subfolder to index faces . 

We will love to test the savant in 4 - 10 camera feeds and looking the 100.000 faces indexed to see a handy benchmark to compare with current solutions both accuracy  speed and easy usage.
Best

**Comment by bwsw** [comment]
@MyraBaba demo is provided AS IS. The interested party must do all the customizations, or we do them commercially.

PR is highly welcome if you make improvements and want to share your results with the community. I'll close the issue as it no longer relates to a bug.
