### ISSUE TITLE
Memory leak in Face ReID demo

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#456]
Fix memory leak

**Comment by abramov-oleg** [comment]
I've prepared a minimal reproducible example in the linked branch.

In a minimal pipeline with nothing except a single pyfunc the leak seems to depend only on using the asynchronous version of `cv2.cuda.alphaComp()`. It manifests even with frame paddings completely disabled.

The 0.2.4-6.2 ver of Savant also manifests the same leak.

To reproduce, first start `nvtop`, then run

```
./samples/memleak/run.sh
```

Optionally, increase the number of buffers in the `videotestsrc` element to make the leak more apparent.

**Comment by abramov-oleg** [comment]
Added a script that reproduces the leak outside the Savant/DS pipeline environment.

```
./samples/memleak/run_script.sh
```

**Comment by bwsw** [comment]
The issue is fixed by #461
