### ISSUE TITLE
Face ReID demo hangs on error

### ISSUE THREAD

**Issue by denisvmedyantsev** [insight-platform/Savant#466]
It can be reproduced under the conditions described in #465 or under the conditions described below.

Use, for example, `./scripts/run_module.py` to start the demo with `module_performance.yml` config. 

To reproduce, modify the face_preproc.py, and raise an exception. If an exception occurs, the module will not terminate after the source has been processed and the module container will go to the "unhealthy" status after some time.

**Comment by bwsw** [comment]
@tomskikh if not in dev mode, pipeline must terminate on exeption.

**Comment by tomskikh** [comment]
Pipeline stuck at setting the state to `NULL` at `[NvMultiObjectTracker] De-initialized`. I've added a timeout for shutdown. Also I've added error reporting to pad probes in `buffer_processor` so the module would stop after it got an error in a pad probe.
