### ISSUE TITLE
Failed to validate seq_id in traffic_meter with output frame h264 software encoder on NX

### ISSUE THREAD

**Issue by denisvmedyantsev** [insight-platform/Savant#473]
To reproduce, add in the `module.yml` of samples/traffic_meter to the `output_frame` parameter `encoder: software`, and run the demo, as described in README.

Logs:
```
...
traffic_meter-module-1             |  INFO  insight::savant::traffic_meter-peoplenet             > Added source town-centre-processed
traffic_meter-always-on-sink-1     | Output town-centre-processed: Processed 1000 frames, 30.00 FPS.
traffic_meter-video-loop-source-1  | Processed 1000 frames, 25.03 FPS. Source location: /tmp/video-loop-source-downloads/savant-data/demo/AVG-TownCentre.mp4.
traffic_meter-always-on-sink-1     | Output town-centre-processed: Processed 1000 frames, 30.00 FPS.
traffic_meter-grafana-1            | logger=infra.usagestats t=2023-10-04T15:13:34.893995819Z level=info msg="Usage stats are ready to report"
traffic_meter-module-1             |  WARN  savant_rs::message::validate_seq_iq                  > Failed to validate seq_id=745 for town-centre-processed, expected=726. SeqId discrepancy is a symptom of message loss.
traffic_meter-module-1             |  WARN  savant_rs::message::validate_seq_iq                  > Failed to validate seq_id=792 for town-centre-processed, expected=770. SeqId discrepancy is a symptom of message loss.
traffic_meter-module-1             |  WARN  savant_rs::message::validate_seq_iq                  > Failed to validate seq_id=844 for town-centre-processed, expected=817. SeqId discrepancy is a symptom of message loss.
...
```

**Comment by bwsw** [comment]
0. validate with software codec on PC (+ video sink)
1. problem on NX (+ video sink)
2. Discord discussion on Jetson Orin Nano

**Comment by elfar** [comment]
To replicate traffic_meter on Orin Nano Dev. All files are as per default in the samples/traffic_meter except module.yml and the docker compose file. Here are those files as well as the container logs for loop, module and sink.
[docker-compose.l4t.yml.jsonsink.txt](https://github.com/insight-platform/Savant/files/12813909/docker-compose.l4t.yml.jsonsink.txt)
[module.yml.txt](https://github.com/insight-platform/Savant/files/12813910/module.yml.txt)
[sink.log](https://github.com/insight-platform/Savant/files/12813937/sink.log)
[loop.log](https://github.com/insight-platform/Savant/files/12813938/loop.log)
[module.log](https://github.com/insight-platform/Savant/files/12813939/module.log)

**Comment by tomskikh** [comment]
I'm receiving an error on always-on-sink with `encoder: software`:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/savant/gstreamer/runner.py", line 72, in _main_loop_run
    raise RuntimeError(self._error)
RuntimeError: Received error "gst-resource-error-quark: Failed to process frame. (1)" from nvv4l2decoder0. Debug info: "gstv4l2videodec.c(2273): gst_v4l2_video_dec_handle_frame (): /GstPipeline:input-pipeline/GstDecodeBin:decodebin0/nvv4l2decoder:nvv4l2decoder0:
Maybe be due to not enough memory or failing driver".
```

Software code + video sink does work.

**Comment by elfar** [comment]
> I'm receiving an error on always-on-sink with `encoder: software`:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/savant/gstreamer/runner.py", line 72, in _main_loop_run
>     raise RuntimeError(self._error)
> RuntimeError: Received error "gst-resource-error-quark: Failed to process frame. (1)" from nvv4l2decoder0. Debug info: "gstv4l2videodec.c(2273): gst_v4l2_video_dec_handle_frame (): /GstPipeline:input-pipeline/GstDecodeBin:decodebin0/nvv4l2decoder:nvv4l2decoder0:
> Maybe be due to not enough memory or failing driver".
> ```

Was asking into this the other day, as far as I recall always-on-sink is not supported for software encoding, only the module.

Bonus info in general, was testing this on X86 and

this does not work
- LOCATION=/results

however, this does work
- LOCATION=/results/%source_id-%src_filename 

I can not get the same code to work on Orin Nano - central error in sink seems to be

DEBUG insight::savant::utils::zeromq                > Timeout exceeded when receiving the next frame

which I am seeing where I see am seeing "Writing meta to file" on x86 instead in the sink container logs

**Comment by tomskikh** [comment]
@elfar 

> Was asking into this the other day, as far as I recall always-on-sink is not supported for software encoding, only the module.

Yes, always-on-sink supports only HW encoder. I've set software encoder on the module.

> this does not work
> 
> * LOCATION=/results
> however, this does work
> 
> * LOCATION=/results/%source_id-%src_filename

You need to specify a file in the `LOCATION`, not a directory. `LOCATION=/results/meta.json` - this should work.

**Comment by elfar** [comment]
It was unclear whether this should be directory or directory/some_prefix or filename.

LOCATION = /results/%source_id-%src_filename
or
LOCATION = /results/meta.json

both do work on x86 (using location as a prefix).

However, neither works on Orin Nano.

**Comment by tomskikh** [comment]
Probably the issue is a workaround for a bug: https://forums.developer.nvidia.com/t/nvv4l2h264enc-returns-frames-in-wrong-order-when-pts-doesnt-align-with-framerate/257363/6.
https://github.com/insight-platform/Savant/blob/760fed6c72424258786c273293c424777430ec0e/savant/deepstream/buffer_processor.py#L955-L965
We need to turn it off for software encoder.

**Comment by tomskikh** [comment]
[This commit](https://github.com/insight-platform/Savant/commit/209ec07128bfa7c10e890db725f2889fa23d56cc) fixed the issue on Jetson NX.

Measured of performance of software encoder on Jetson NX using DEALER-ROUTER sockets and `SYNC_OUTPUT=False`:
- Only source and module (without sink and grafana) - 19 FPS.
- Full sample with always-on-sink - 15 FPS. Also always-on-sink cannot decode frames from software encoder on Jetson NX: https://github.com/insight-platform/Savant/issues/473#issuecomment-1748381653.
- Full sample but with video-file-sink instead of always-on-sink - 16 FPS.

**Comment by elfar** [comment]
Hi - is it possible that this issues also exists for codec=jpeg? When using 

/opt/savant/adapters/python/sinks/image_files.py

I am experiencing the same result at least. Getting no files saved with .l4t code but seeing files with the equivalent .x86 code

**Comment by bwsw** [comment]
@elfar please open an issue and describe the situation and configuration of the pipeline in detail.

**Comment by elfar** [comment]
This may actually be a lib_version issue on the jetson device. Will do a fresh docker images start there and have a closer look at debug now that I enabled that loglevel before creating any new issue

**Comment by bwsw** [comment]
@elfar ok, keep us in touch. We mainly focused on the module encoder and fixed many caveats related to Jetson, but they can be in sinks, too.
