### ISSUE TITLE
Extend in-GPU image dimensions to add spare space for cropped and exogenous elements placement

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#48]
Create a plugin that allows the user to specify additional graphical space on the image filled with blank **black** color and is used to place temporary graphical objects used in secondary inference steps. The primary ROI must include the initial frame area, while the extended area must be used only for utility operations.

There must also be settings configuring a mirror operation - the plugin removes excessive space.

E.g.

```
Muxer: WxH
(optional) canvas-size: {top, left}, Wx(H+N)
...
(optional) canvas-size:  {top, left}, WxH
Demuxer: WxH
```

**Comment by denisvmedyantsev** [comment]
The main idea is to get custom pre-processing. For this, we can try to use [NvDsPreProcessTensorMeta](https://docs.nvidia.com/metropolis/deepstream/dev-guide/sdk-api/structNvDsPreProcessTensorMeta.html)

**Comment by bwsw** [comment]
@denisvmedyantsev it looks irrelevant to me. Because the feature is not solely about inference preprocessing but also about the possibility of adding placeholders for metadata information, branding, etc, outside the image region. Also, certain preprocessing operations may include complex preprocessing that is not covered by nVidia, like RGB2GRAY or color correction. Thus I believe that the regions where the user can safely place the objects to use them somehow may be beneficial.
