### ISSUE TITLE
Draw func won’t draw track ID when draw func in a separate container

### ISSUE THREAD

**Issue by tomskikh** [insight-platform/Savant#502]
When draw_func in the same container with the tracker it draws track IDs on labels:

```
docker compose -f samples/draw_func_track_id_bug/docker-compose-single-container.x86.yml up
```

![Screenshot from 2023-10-17 12-16-59](https://github.com/insight-platform/Savant/assets/8089582/f1b8435d-90ac-425a-a0d2-959e3dba0096)

But when draw_func in a separate container it doesn't draw track IDs:

```
docker compose -f samples/draw_func_track_id_bug/docker-compose-separate-draw-func.x86.yml up
```

![Screenshot from 2023-10-17 12-19-21](https://github.com/insight-platform/Savant/assets/8089582/b8c5a7bf-c184-4f54-84b5-7ffc1a6eb46d)

---

The sample to reproduce bug can be found in a commit https://github.com/insight-platform/Savant/commit/87c2bd8b380e7977fc367c5e6e9d40d1f2c11048.

**Comment by denisvmedyantsev** [comment]
We get track_id=None from the input video object [here](https://github.com/insight-platform/Savant/blob/566ef41a10ee90719c8ad148f15669d729028c7f/savant/deepstream/buffer_processor.py#L232), even though the object contains a numeric track_id (if we print the object)

@bwsw Perhaps there is a problem in the method get_track_id https://github.com/insight-platform/savant-rs/blob/4bb4ece19a1fa0969607d36f996a224895905402/savant_python/src/primitives/object.rs#L55
