### ISSUE TITLE
Document how to customize tracking postprocessing

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#524]

**Comment by abramov-oleg** [comment]
From #507 

Added a disable-obj-init config key for nvtracker elements' properties. The value by default is false to avoid introducing any changes to current behavior. Example:

    - element: nvtracker
      properties:
        tracker-width: 640
        tracker-height: 384
        ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
        # specify tracking config file
        ll-config-file: ${oc.env:PROJECT_PATH}/samples/peoplenet_detector/config_tracker_NvSORT.yml
        disable-obj-init: true

If the disable-obj-init is set to true for a given nvtracker element a src pad (output) probe will be added to it before adding the element to the pipeline. The probe iterates DS metadata structures looking for objects that were created by nvtracker and removes them.
