### ISSUE TITLE
Fix docs links

### ISSUE THREAD

**Issue by denisvmedyantsev** [insight-platform/Savant#566]
We have some documents in Markdown format in the docs/ folder. E.g. [adapters.md](https://github.com/insight-platform/Savant/blob/develop/docs/adapters.md). The documents contain links to the documentation in the old format, without a version (so they redirect to the latest documentation root page). Moreover, there is a link to one of these documents in almost every sample readme

> Ubuntu 22.04 runtime configuration [guide](../../docs/runtime-configuration.md...

We can 1) Remove markdown documents and links to them OR 2) Support some kind of permalinks

**Comment by bwsw** [comment]
Let us remove them.
