### ISSUE TITLE
Incorrect build engines section in pass-through sample

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#577]
The section states that you must run:

```
./scripts/run_module.py --build-engines samples/peoplenet_detector/module.yml
```

but it does not look relevant.

**Comment by denisvmedyantsev** [comment]
Some of our samples re-use models of other samples, this sample for example, https://github.com/insight-platform/Savant/blob/develop/samples/pass_through_processing/docker-compose.x86.yml#L30
