### ISSUE TITLE
Pub/Sub topic filtering

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#59]
This is an optimizing feature, that decreases the amount of traffic sent to wrong destinations.

Zero MQ's  Pub/Sub implements a topic filtering feature. The Subscriber can specify the topic prefix which causes that the only matching topics are being processed. The feature is only available for `pub` or `sub` socket types, but ZeroMQ transparently handles other kinds of generally compatible sockets without topic filtering as well.

We have to support the feature based on stream `source_id` concept. So, when the publisher of any kind (source adapter or framework) publishes the messages to pub/sub it must specify `source_id` as `topic_name`.

When the subscriber of any kind (framework or sink adapter) is configured it can optionally specify topic prefix to filter out only matching topics. For the framework the prefix may be specified in a YaML configuration, for sink adapter it may be specified as an argument or if adapter is designed to support only the kind of operation for a single `source_id`, then topic filter must be set to `source_id`.

Summary:
* multiplexed sinks/framework input: source_id prefix or source_id;
* single stream sinks: source_id
* publishers (source adapter, framework output): source_id > topic

To create corresponding tests.

From ZMQ GitHub: https://github.com/zeromq/libzmq/issues/3611

**Comment by tomskikh** [comment]
Implemented frames filtering for any zmq socket type. Messages are send with `socket.send_multipart(["source_id/", avro_msg])`.
