### ISSUE TITLE
RTSP stream as output and custom functions

### ISSUE THREAD

**Issue by HtutLynn** [insight-platform/Savant#6]
First of all, thanks for the amazing repo!

I am a beginner in DeepStream and currently learning Savant to convert pytorch-based multi-streamsCV analytics pipeline to DeepStream/Savant based pipeline to improve runtime performance on Jetson devices. I want to implement custom functions such as line-cross counting similar to [sample video](https://youtu.be/gs9cy2XfCBA) and also want to stream outputs as RTSP stream. Also, I want to upload counted results to Azure CosmosDB or Firebase in interval. I am struggling to integrate these functions to Savant and kinda lost on where to start right now. Can you please guide me on this? Thanks in advance!

**Comment by bwsw** [comment]
Hello, @HtutLynn we haven't yet officially published Savant. In the nearest days, we will finally publish it and provide live examples and a Medium article on how to use it. I will keep you posted.

**Comment by HtutLynn** [comment]
@bwsw , that is really helpful! I am really looking forward to the official publication of Savant along with examples and docs. Would love to contribute too!

**Comment by bwsw** [comment]
Outdated
