### ISSUE TITLE
Always-On Low Latency Streaming Sink (RTSP)

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#60]
Always-on RTSP sink implements stable RTSP server that delivers streaming frames when they present or stub picture when there is no incoming data.

# General 

The module handles only one `source_id` which is specified upon the module launch. If the module is run as `sub`, topic filtering is used, when it is launched with another kind of socket, the filtering happens based on metadata `source_id`.

The module supports publishing to streaming media server like Aler9 RTSP frontend, Aler9 must be delivered and launched within a separate container like here: https://github.com/insight-platform/Fake-RTSP-Stream/blob/main/docker-compose.yml

# Stub Producer

A user specifies a stub picture in the form of a jpeg file. The resolution of the stub picture defines the resolution of the output RTSP stream. When there is no incoming data, the module places the current date/time in the user-format to the top-right corner (white on black). The format for date-time is specified by the user with command line argument.

The stub picture is displayed in two cases:

* when the module is started and there are no incoming frames;
* when the incoming frame stream doesn't update frames for X milliseconds (default: 1000, which is specified by the user with command line argument).

# FPS and Quality

The module always delivers output stream with a fixed FPS (default 30) and a encoding profile (default high) specified with command line arguments. No matter either incoming stream produces frames or it is doesn't deliver anything, the module generates the outgoing stream with those parameters.

**NB**: If the encoding profile doesn't work due to a DeepStream [error](https://forums.developer.nvidia.com/t/rtsp-stream-sent-by-rtspclientsink-doesnt-play-in-deepstream-6-2/244194), try to replace it with the bitrate configuration.

# Proposed Architecture

The module consists of two threads:
* output thread, which generates black-background stub, optionally replaces it with either real-stream image OR stub picture (with date-time), and generates RTSP output (NVENC).
* input thread, which decodes incoming frames (NVDEC), places them to GpuMat, which can be  and updates the last-time counter.

![image](https://raw.githubusercontent.com/insight-platform/Savant/develop/docs/AA%20RTSP%20sync.drawio.png)

It looks like the both pipelines may heavily reuse current Savant codebase.

# Image Alignment

When a stream image is positioned within the black-background stub image. There are two modes (`scale-to-fit` or `crop-to-fit`).
* `scale-to-fit`: scale with interpolation and aspect preservation fit the smallest dimension (width or hight). To fit well it must be scaled up or down. This is necessary to not limit incoming streams to specific resolutions;
* `crop-to-fit`: crop to fit the canvas and place in the central position.

# Metadata Processing

The module handles the metadata in two ways:
* unconditional drop;
* filtering the `source_id` and dumping the metadata to standard output as formatted JSON structures.

**Comment by tomskikh** [comment]
`rtspclientsink` doesn't work properly on Deepstream 6.2. I posted a bug to nvidia forum https://forums.developer.nvidia.com/t/rtsp-stream-sent-by-rtspclientsink-doesnt-play-in-deepstream-6-2/244194

**Comment by bwsw** [comment]
@tomskikh Can we try RTMP as an option, and later add RTSP when it is fixed?

**Comment by tomskikh** [comment]
> Can we try RTMP and WEBRTC (webrtcbin) as an option, and later add RTSP when it is fixed?

RTMP has the same issue. I found out the issue appears only on low latency presets of nvv4l2h264enc.

**Comment by bwsw** [comment]
@tomskikh so we can avoid low latency preset right now and move forward?

**Comment by tomskikh** [comment]
@bwsw Yes.
