### ISSUE TITLE
Modifying Object Attributes 

### ISSUE THREAD

**Issue by Y-T-G** [insight-platform/Savant#605]
I know we can get and add an attribute to an object. But I wanted to know how to modify an already added attribute. I tried adding it again with the same namespace and element_name, but I don't see the updated attribute in the draw_func. However, I can see it in the metadata retrieved in Client SDK

**Comment by denisvmedyantsev** [comment]
The current attribute storage scheme allows multiple values to be stored for a single key (model name, attribute name). This is used to store multiple values for a multi-label classifier. So we don't have a method to change/drop a value, only to add a new one. You can get all values for the key with `get_attr_meta_list` (`get_attr_meta` returns only the first value added). 

In your case, you can use a different key (model name, attribute name) to store the new value or process the entire list of added values correctly.

**Comment by denisvmedyantsev** [comment]
We will add a method for deleting/replacing an attribute value (the entire list of values) soon. I'll post here.
