### ISSUE TITLE
No property `first-moov-then-finalise` in element `qtdemux`

### ISSUE THREAD

**Issue by Y-T-G** [insight-platform/Savant#608]
If I remove the property from https://github.com/insight-platform/Savant/blob/b3a12f959ab60595fe8b683f430aa57ce50f7a97/adapters/gst/gst_plugins/python/video_files_sink.py#L87, it works.

**Comment by Y-T-G** [comment]
No property `fragment-mode` in element `qtdemux`

**Comment by tomskikh** [comment]
@Y-T-G Could you please clarify what doesn't work with that property? `video_files_sink` uses `qtmux`, not `qtdemux`. And `qtmux` has the property `fragment-mode`:

```
  fragment-mode       : How to to write fragments to the file.  Only used when 'fragment-duration' is greather than 0
                        flags: readable, writable
                        Enum "GstQTMuxFragmentMode" Default: 0, "dash-or-mss"
                           (0): dash-or-mss      - Dash or Smoothstreaming
                           (1): first-moov-then-finalise - First MOOV Fragment Then Finalise
```

**Comment by Y-T-G** [comment]
@tomskikh Yes, sorry. I meant `qtmux`. I don't see that property when I check.

![image](https://github.com/insight-platform/Savant/assets/32206511/8ef43caf-f760-4750-a7fc-21858af7186e)

I am using ghcr.io/insight-platform/savant-adapters-deepstream:latest.

**Comment by tomskikh** [comment]
@Y-T-G Use `ghcr.io/insight-platform/savant-adapters-gstreamer:latest` for video files sink.

**Comment by Y-T-G** [comment]
@tomskikh Thanks
