### ISSUE TITLE
Cannot run Always-On Sink adapter in Docker on A100

### ISSUE THREAD

**Issue by cookiego** [insight-platform/Savant#637]
Guys, hello!

Please, help me =)
I'm trying to implement sample kafka-redis-pipeline in docker on A100 in cloud.
All containers are running OK except the Always-on Sink.
There was such an error for module container at its start (it also failed and terminated), but changing demo.yml and setting from nvenc to software resolved the issue.
So, my question, how to force adapter container to use software encoding without building from my own dockerfile or smth?

Logs are saying:

(gst-plugin-scanner:29): GStreamer-WARNING **: 23:09:16.328: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstmpeg2enc.so': libmpeg2encpp-2.1.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:29): GStreamer-WARNING **: 23:09:16.364: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstmpeg2dec.so': libmpeg2.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:29): GStreamer-WARNING **: 23:09:17.561: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_ucx.so': libucs.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:29): GStreamer-WARNING **: 23:09:17.581: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_udp.so': librivermax.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:29): GStreamer-WARNING **: 23:09:17.595: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_inferserver.so': libtritonserver.so: cannot open shared object file: No such file or directory
 INFO  insight::savant::adapters::ao_sink::entrypoint > NVIDIA runtime is available. Using hardware-based decoding/encoding.
 INFO  insight::savant::deepstream::encoding          > Checking if encoder for codec 'h264' is available
 INFO  insight::savant::gstreamer::runner             > Starting pipeline `<Gst.Pipeline object at 0x7fd45a4ed800 (GstPipeline at 0x359c120)>`...
 INFO  insight::savant::gstreamer::runner             > The pipeline is initialized and ready to process data. Initialization took 0:00:00.002056.
ENC_CTX(0x7fd43400f800) Error in initializing nvenc context 
 ERROR insight::savant::gstreamer::runner             > Received error "gst-resource-error-quark: Could not get/set settings from/on resource. (13)" from nvv4l2h264enc0. Reached the limit of encoders sessions.
 INFO  insight::savant::gstreamer::runner             > The pipeline is about to stop. Operation took 0:00:00.002553.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/savant/gstreamer/runner.py", line 75, in _main_loop_run
    raise RuntimeError(self._error)
RuntimeError: Received error "gst-resource-error-quark: Could not get/set settings from/on resource. (13)" from nvv4l2h264enc0. Reached the limit of encoders sessions. Debug info: "gstv4l2object.c(3536): gst_v4l2_object_set_format_full (): /GstPipeline:pipeline0/nvv4l2h264enc:nvv4l2h264enc0:
Device is in streaming mode".
 ERROR insight::savant::deepstream::encoding          > You have configured NVENC-accelerated encoding, but your device doesn't support NVENC.

**Comment by bwsw** [comment]
Hello, read this, not a bug: 

https://docs.savant-ai.io/develop/savant_101/10_adapters.html#always-on-rtsp-sink-adapter

**Comment by cookiego** [comment]
I suppose it seems not able to detect that A100 in place does not support hardware encoding.
I pull ghcr.io/insight-platform/savant-adapters-deepstream:latest images and i read in docs there was like a failback to software encoding, but in logs I see that it successfully detected hardware

**Comment by bwsw** [comment]
Here is the error. A100 does not have NVENC on board:

ERROR insight::savant::deepstream::encoding > You have configured NVENC-accelerated encoding, but your device doesn't support NVENC.

**Comment by bwsw** [comment]
https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

**Comment by cookiego** [comment]
Hmmm, as far as I can see you are saying to me that I should disable Nvidia Runtime for that container. Ok I'll try that way, but I have a docker swarm configuration, so the runtime now is activated as a whole for the swarm, not sure about concrete containers.
I'll check and return.
Thank you!

**Comment by cookiego** [comment]
> Here is the error. A100 does not have NVENC on board:
> 
> ERROR insight::savant::deepstream::encoding > You have configured NVENC-accelerated encoding, but your device doesn't support NVENC.

Sure i understand this. It is written in Savant's docs that A100 does not support NVENC. My question is that when i run docker container on A100 if fails to start (even it is supposed to switch to software encoding). But, yes, maybe my docker swarm config forces to use nvidia runtime\hardware encoding even if real harware does not support it

**Comment by bwsw** [comment]
Yes, you must disable gpu resources for this particular container.

**Comment by bwsw** [comment]
Or you can build your own AO-RTSP based on our container code.

**Comment by cookiego** [comment]
> Or you can build your own AO-RTSP based on our container code.

Yes, indeed, I'll try that.
Just for somebody with the same prob at this time. What i've found is that currently when you are in swarm mode of docker, there's not support for setting 'runtime' on per-container basis in your .yaml. So the only way to use NVIDIA\CUDA hardware support inside container is to set the 'default-runtime' in docker daemon.json, which in my case (starting AO-RTSP fails saying it has hardware support but it is busy, when there's no hardware support at all...)
So, I'll try to build custom thing.

Thank you!

**Comment by bwsw** [comment]
Hm, the problem is not about the runtime, but only resource deployment. Does not swarm allows that?

**Comment by patrickhulce** [comment]
I'm getting this same error on a Windows device in WSL even though my graphics card (GTX 4070) definitely supports NVENC (it does within WSL, but apparently these docker images can't detect / use it). Any guidance / troubleshooting advice here to debug further?

**Comment by bwsw** [comment]
@patrickhulce hello WSL is not fully supported by DeepStream and, thus, Savant.

**Comment by patrickhulce** [comment]
Thanks @bwsw !
