### ISSUE TITLE
Quality and Bitrate Configuration for Savant Output Frame 

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#66]
Allow setting bitrate and Quality profile for H264, H265, and other supported video codecs.

**Comment by bwsw** [comment]
Check and document how to use that.

**Comment by abramov-oleg** [comment]
All the properties for each of supported encoder elements can already be set through `parameters.output_frame.encoder_params` module config node.

Described this option in documentation in a new section on `Module overview` page.
