### ISSUE TITLE
Add python profiling to Savant

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#67]
Add an option to run a code with profiling with: https://github.com/gaogaotiantian/viztracer

The feature allows monitoring the code for bottlenecks and awaiting for GIL in various components.

By default, the profiling is disabled.

Use inline profiling: 
https://github.com/gaogaotiantian/viztracer#inline

The tracing must be optionally enabled with the use of arguments (e.g. `--with-profiling` or with a parameter in the config or with the environment variable `SAVANT_PROFILING=enable`. 

The periodicity of the profile dump must be implemented with the extra parameter `--profiling-dump-interval=5` or with or with a parameter in the config (default 5). 

When the profiling file is dumped, the name must be constructed using the timestamp: `/tmp/profiling/savant-profiling-%{TS}.json`.

To use the profiling dumps, the user maps the dump directory to a host directory and analyzes the profiling with the `vizviewer` program.

Also support with the configuration directives:
- Min Duration: https://viztracer.readthedocs.io/en/stable/filter.html#min-duration
- Include Files: https://viztracer.readthedocs.io/en/stable/filter.html#include-files
- Exclude Files: https://viztracer.readthedocs.io/en/stable/filter.html#exclude-files
- Sparse Log: https://viztracer.readthedocs.io/en/stable/filter.html#log-sparse
-

**Comment by bwsw** [comment]
@abramov-oleg take a look at this section: https://github.com/gaogaotiantian/viztracer#json-alternative

**Comment by abramov-oleg** [comment]
Unfortunately it wasn't possible to complete the task using `viztracer` out of the box:

1. Viztracer doesn't trace python callbacks from gstreamer C part. As a result, only waiting for next pipeline message was traced.
2. Custom Viztracer events in python callbacks crash the pipeline with no message when using single global tracer object.
3. Creating separate tracer objects for each target function call is not convenient and presents separate problem with combining resulting files.
