### ISSUE TITLE
Switch to a new streammuxer and discard single resolution scaling

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#679]
The new stream muxer allows working with original resolutions without the need to scale image
https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvstreammux2.html

**Comment by tomskikh** [comment]
New stream muxer hangs when config file passed. https://forums.developer.nvidia.com/t/new-nvstreammux-hangs-the-pipeline/301112/7?u=tomskih_pa
