### ISSUE TITLE
Building ReID model engine file bug

### ISSUE THREAD

**Issue by BloomBabe** [insight-platform/Savant#701]
Hello, I'm trying to customize face reid sample app with person reid. So I edit src/module.yml file with my detection and re identification models and run  ./scripts/run_module.py script with ```--build-engines flag```, detection model builds fine, but at building reid engine model stage script unexpectedly crashes withou any logs. When I build reid engine model file with ```trtexec```, it builds fine:

```/usr/src/tensorrt/bin/trtexec` --onnx=/media/hhd/Savant/cache/models/custom_reid/osnet_x0_25_msmt17/osnet_x0_25_msmt17.onnx --saveEngine=/media/hhd/Savant/cache/models/custom_reid/osnet_x0_25_msmt17/osnet_x0_25_msmt17.onnx_b100_gpu0_fp16.engine --minShapes='images':1x3x256x128 --optShapes='images':20x3x256x128 --maxShapes='images':100x3x256x128 --fp16 --workspace=2000 --verbose ```

module.yml : https://drive.google.com/file/d/1OWB4zXwaHDLFEwa91b3mmwYICd7KxeO4/view?usp=sharing
osnet_x0_25_msmt17.onnx : https://drive.google.com/file/d/1qDJNTNIw_jxp1GSgND1Xcd4wnI6HmMD7/view?usp=sharing

**Comment by bwsw** [comment]
With #688

**Comment by bwsw** [comment]
@BloomBabe the bug will be opened on the Nvidia forum. The link to the issue will be here.

**Comment by denisvmedyantsev** [comment]
The problem could not be reproduced outside the Savant. We solved it by fixing the import order for GStreamer packages. @BloomBabe try to use the latest Savant container for your case.
