### ISSUE TITLE
Support metadata in the KVS Sink adapter

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#714]
We must support attaching metadata to enable full-featured transport.

**Comment by bwsw** [comment]
The first and the last UUIDs must be added to the KVS block.

**Comment by tomskikh** [comment]
@bwsw Fragment can contain only up to 10 metadata items: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/limits.html#limits-streaming-metadata

> You can prepend up to 10 metadata items to a fragment.
> A fragment metadata name can be up to 128 bytes in length.
> A fragment metadata value can be up to 256 bytes in length.

So we cannot put frame metadata inside video fragments in KVS. We can only put a link to a metadata in some other storage.
