### ISSUE TITLE
Add keypoints to the protocol

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#73]
The protocol must support the framework's key points (in and out). The key points must be abstract enough to encode various objects, not only persons. Each key point must include 2D coordinates and `id`, which is domain-specific.

**Comment by denisvmedyantsev** [comment]
Current avro (and python code inside Savant) supports flexible [attributes](https://github.com/insight-platform/Savant/blob/develop/savant/api/avro-schemas/payload/VideoFrame/vision.module.Attribute.avsc). We can add key points to the object as an array of floats attribute. Unfortunately, the schema doesn't contain explicit information on how to "understand" each float value (eg. value #5 is x coordinate of person elbow, #6 is y coord, etc.). We also can treat each point as a separate attribute using an array of floats with the length of 2 (x, y), eg. an attribute with the name "elbow" with value [x, y]. Such options are based on the object and the box as the primary object (we can wrap key points with a box). Do you suppose to support key points as a new kind of primary entity? Can you explain and give some use cases?

**Comment by bwsw** [comment]
1. object attribute: `Array[x, y, Array[tags]]`.
2.
