### ISSUE TITLE
Video-loop source adapter won't read DTS from MKV files

### ISSUE THREAD

**Issue by tomskikh** [insight-platform/Savant#742]
Create an MKV file:
```
ffmpeg -i data/Free_City_Street_Footage.mp4 -c:v libx264 -preset medium data/Free_City_Street_Footage.mkv
```

Run a module:
```
./scripts/run_module.py samples/peoplenet_detector/module.yml
```

Run a source adapter with this file:
```
./scripts/run_source.py video-loop --source-id foo --sync --mount-download-path data/Free_City_Street_Footage.mkv
```

The module adds a source and then immediately removes it:
```
 INFO  insight::savant::savant_rs_video_decode_bin          > Adding branch with source foo
 INFO  insight::savant::savant_rs_video_decode_bin          > Branch with source foo added
 INFO  insight::savant::savant_rs_video_demux               > Created new src pad for source foo: src_foo.
 INFO  insight::savant::savant_rs_video_demux               > Timestamps on source foo non-monotonous. Resetting source.
 WARN  insight::savant::savant_rs_video_demux               > Frame 80000000 from source foo is not a keyframe, skipping it. Stream should start with a keyframe.
 WARN  insight::savant::savant_rs_video_demux               > Frame 40000000 from source foo is not a keyframe, skipping it. Stream should start with a keyframe.
 WARN  insight::savant::savant_rs_video_demux               > Frame 120000000 from source foo is not a keyframe, skipping it. Stream should start with a keyframe.
```

It is due to file containing B-frames and video-loop source adapter not sending DTS:
`DEBUG savant_rs::zeromq::writer                             > Sending message to ZeroMQ socket: foo Message { meta: MessageMeta { protocol_version: "0.2.0", routing_labels: [], span_context: PropagatedContext({}), seq_id: 9 }, payload: VideoFrame(VideoFrameProxy { inner: SavantArcRwLock(SavantRwLock(RwLock { data: VideoFrame { previous_frame_seq_id: None, previous_keyframe: None, source_id: "foo", uuid: 2072128069914838950920888203566706869, creation_timestamp_ns: 1714024166160474282, framerate: "25/1", width: 1920, height: 1080, transcoding_method: Copy, codec: Some("h264"), keyframe: Some(false), time_base: (1, 1000000000), pts: 280000000, dts: None, duration: Some(40000000), content: External(ExternalFrame { method: "zeromq", location: None }), transformations: [InitialSize(1920, 1080)], attributes: [Attribute { namespace: "default", name: "location", values: [AttributeValue { confidence: None, value: String("/home/pavel/mi/Savant/data/Free_City_Street_Footage.mkv") }], hint: None, is_persistent: true, is_hidden: false }], objects: {}, max_object_id: 0 } })) }) }`

**Comment by bwsw** [comment]
Please check that it does not happen with MPEG and QT containers serving HEVC/H.264 with B-frames.

**Comment by tomskikh** [comment]
We can add an element that stores frames between keyframes in buffer and then puts DTS to them. Similar to [NvDsJetsonH26XBufferProcessor](https://github.com/insight-platform/Savant/blob/3e211bed3c154dc23ed587b999323106e09552fc/savant/deepstream/buffer_processor.py#L645C7-L645C36).
