### ISSUE TITLE
Trying to implement a converter for specialized model.

### ISSUE THREAD

**Issue by chanwitkepha** [insight-platform/Savant#784]
My developer team are trying to implement a converter for our specialized model. Looking at your sample converters such as AgeGenderConverter and LPRNetOutputConverter, it seems like the classes expect outputs from these models as if there is only one instance of output and there are no batch dimension. Do we understand correctly? 

```
class AgeGenderConverter(BaseAttributeModelOutputConverter):
    def __call__(
        self,
        *output_layers: np.ndarray,
        model: AttributeModel,
        roi: Tuple[float, float, float, float],
    ) -> List[Tuple[str, Any, Optional[float]]]:
        """Converts age gender model output vector to age and gender attribute."""
        age = np.sum(np.multiply(output_layers[0], age_range)).item()
        gen = int(np.argmax(output_layers[1]).item())
        return [
            (model.output.attributes[0].name, age, None),
            (
                model.output.attributes[1].name,
                GENDER_MAPPING[gen],
                float(output_layers[1][gen].item()),
            ),
        ]
```

**Comment by bwsw** [comment]
@denisvmedyantsev could you comment please.

**Comment by denisvmedyantsev** [comment]
Yes, you got that right. The converter works on a frame-by-frame basis.

**Comment by chanwitkepha** [comment]
> Yes, you got that right. The converter works on a frame-by-frame basis.

Thank you for your answer.
