### ISSUE TITLE
Enabling `USE_ABSOLUTE_TIMESTAMPS` causes `Sink queue is full` message on ffmpeg adapter on 0.2.10

### ISSUE THREAD

**Issue by heyryanw** [insight-platform/Savant#791]
We have a pipeline topolgy that looks like so:

RTSP camera on ffmpeg adapter|dealer+connect > router+bind|Buffer adapter|dealer+connect > router+bind|Module

Everything flows and works fine on this setup without issue. 

Enabling `USE_ASBSOLUTE_TIMESTAMPS=True` on the FFmpeg adapter immediately outputs a `Sink queue is full, the frame is skipped` message, with no messages reaching the buffer adapter, confirmed by checking the Prometheus stats of the adapter all being 0.

Disabling, everything works fine again.

**Comment by bwsw** [comment]
Check and fix in 0.2.11, develop.

**Comment by tomskikh** [comment]
@heyryanw Could you send a compose file to reproduce the issue? I've tried to change `samples/buffer_adapter/docker-compose.x86.yml`, but everything works fine.

[docker-compose.x86.yml.txt](https://github.com/user-attachments/files/15983192/docker-compose.x86.yml.txt)
