### ISSUE TITLE
Question about implementing with numpy or softmax?

### ISSUE THREAD

**Issue by chanwitkepha** [insight-platform/Savant#792]
Question from our developer team, We have to do some post processing such as computing Softmax over tensor outputs of our model. 

We normally utilize torch’s softmax. In Savant it seems like outputs are in numpy array format. 

Should we convert this numpy array to tensor and use torch softmax or implement softmax over numpy array? Which is more efficient?

Thank you for your kindly help.

**Comment by bwsw** [comment]
@chanwitkepha hello. Unfortunately, We do not consult on 3rd-party products and their efficiency. You try different approaches and choose what works best for you. Also, I recommend joining our Discord where you can get the answer from channel users.
