### ISSUE TITLE
Cut video stream to size-fixed videos

### ISSUE THREAD

**Issue by OrionChocoPie** [insight-platform/Savant#795]
I recently started using your cool tool. Does your tool allow you to cut the incoming video stream into several videos of a fixed size and feed it into the model?
And can I write my own video classifier that will process videos?

**Comment by bwsw** [comment]
Hello, 

- you can slice the video with FFmpeg.
- probably you can. I do not understand the approach - if you want to ask practical domain-related questions, you can join our Discord community.

Best wishes
