### ISSUE TITLE
Trying to export my custom yolov7 model from .pt to .onnx 

### ISSUE THREAD

**Issue by chanwitkepha** [insight-platform/Savant#796]
Dear all, I'm trying to export my custom yolov7 model from .pt to .onnx to be used in Savant. 
Should I export with nms included or not? It seems like the yolo converter in Savant doesn’t handle the case with nms included.

Thank you in advance for your help.

**Comment by bwsw** [comment]
Please ask use case questions on Discord. Here we mostly handle bugs, complex cases and features.
