### ISSUE TITLE
Segmentation Fault from module/run.py when running uri-input.py 

### ISSUE THREAD

**Issue by Nachiket-ML** [insight-platform/Savant#822]
I am trying to follow the instructions from this Savant tutorial: https://www.youtube.com/watch?v=jIntvew3QaI

When I start the uri-input.py script from this doc under the VS Code section (https://github.com/insight-platform/Savant/tree/develop/samples/template), I get a Segmentation Fault in the module/run.py output. 
```
 INFO  insight::savant::gstreamer::runner                   > The pipeline is initialized and ready to process data. Initialization took 0:00:19.579966.
 INFO  insight::savant::healthcheck::status                 > Setting module status to ModuleStatus.RUNNING.
 INFO  insight::savant::utils::zeromq                       > Starting ZMQ source.
 INFO  insight::savant::savant_rs_video_decode_bin          > Adding branch with source test
 INFO  insight::savant::savant_rs_video_decode_bin          > Branch with source test added
 INFO  insight::savant::savant_rs_video_demux               > Created new src pad for source test: src_test.
Running in WSL
 INFO  insight::savant::template                            > Added source test
 INFO  insight::savant::src::module::custom_pyfunc          > frame meta object: <savant.meta.object.ObjectMeta object at 0x7fe0b63a8c10>
 INFO  insight::savant::src::module::custom_pyfunc          > Processing frame #0 of source test..
Segmentation fault
```
My dev container setup uses docker desktop with WSL 2 backend, which is where I am running the jaeger and always-on-sink containers. The always-on-sink container uses the latest version of the savant-adapters-deepstream image - [ghcr.io/insight-platform/savant-adapters-deepstream](app://dd/dashboard/images/local/details?tag=latest&name=ghcr.io%2Finsight-platform%2Fsavant-adapters-deepstream). 

I'd like to fix this error as soon as possible. What is the cause of this error? How can I fix it? Please let me know as soon as possible.

**Comment by bwsw** [comment]
Hello. WSL2 is not supported by DeepStream 6.4 and Savant, either.

**Comment by Nachiket-ML** [comment]
How do I install native Ubuntu 22.04 on Windows? I tried using Oracle VirtualBox but it has no GPU passthrough. Do you know of any VM that can access my windows GPU?

**Comment by bwsw** [comment]
GPU pass-through is possible with Linux in Windows. Unfortunately, we cannot help with that.
