### ISSUE TITLE
symmetric-padding support

### ISSUE THREAD

**Issue by pranavsrihari123** [insight-platform/Savant#830]
I believe I made the necessary changes in the savant codebase to include symmetric-padding support, but I get this error:
<img width="1060" alt="Screen Shot 2024-08-06 at 5 19 48 PM" src="https://github.com/user-attachments/assets/1c351669-bc46-44a3-9250-c3c0e9c98f20">

I believe omegaconf is not recognizing the changes? Any guidance on how to include symmetric-padding support?

**Comment by bwsw** [comment]
You are right that there is no key 'symmetric_padding'. So far, you can use it only when you pass it with Nvinfer config directly, but not with YAML. 

Samples of how to do that are here: https://github.com/insight-platform/Savant/tree/develop/samples/nvidia_car_classification/flavors

However, we will implement the parameter shortly. If you like you can track the issue and see when it is closed in a couple of days.

**Comment by bwsw** [comment]
@placccebo you can take a look here on how to do that: https://github.com/insight-platform/Savant/pull/816

There is a parameter function in the codebase for 'bool' which supports all True/False, Yes/No, Y/N, etc.

You must implement it in the same scope as `input.maintain_aspect_ratio`. Use your identity demo to check that the function is implemented correctly (you can update your identity to demonstrate both parameters).

**Comment by bwsw** [comment]
@pranavsrihari123 hi. The feature is merged. 

A sample of the use can be found here: https://github.com/insight-platform/Savant/tree/develop/samples/bypass_model

Please wait until the job to complete: https://github.com/insight-platform/Savant/actions/runs/10283152157

After that, pull updated containers.

**Comment by bwsw** [comment]
@pranavsrihari123 this job: https://github.com/insight-platform/Savant/actions/runs/10284461471

**Comment by pranavsrihari123** [comment]
Excellent, thanks
