### ISSUE TITLE
Unable to get the stream: no one is publishing to path 'stream'

### ISSUE THREAD

**Issue by ramesh-xinthe** [insight-platform/Savant#887]
Hi @tomskikh 

Hope you are doing well.

While Trying to work with Savant (v0.4.8) Traffic Meter Getting an error "no one is publishing to path 'stream'" and unable to get the stream in web browser and RTSP also could you please help on this issue 

In RTSP it is showing the timer but unable to get the video output So far
Note: I'm trying to run Savant compose file in windows docker-desktop ( WSL2 ubuntu-22.04 )

Here is my system details:

Windows 11
Docker Desktop
WSL2 Ubuntu-22.04
NVIDIA GeForce RTX 4060

![image](https://github.com/user-attachments/assets/d9b5caa9-0c31-4239-b77f-4a6ba81c08ee)

![image](https://github.com/user-attachments/assets/f2f60f41-b9d5-43a5-9502-20c564d958cf)

![image](https://github.com/user-attachments/assets/e08b2f16-d5b3-485d-84f1-653d0b06bb2b)

Thanks & Regards
Ramesh

**Comment by bwsw** [comment]
Hi. WSL2 is not supported by Savant 0.4.x

**Comment by ramesh-xinthe** [comment]
Hi @bwsw 

Thanks for the quick response. Could you please help me to find the working version of Savant for WSL2.

Actually i was tried with Savant 0.2.2 in WSL2 But no luck 

reference blog url:

https://blog.savant-ai.io/efficient-city-traffic-metering-with-peoplenet-yolov8-savant-and-grafana-at-scale-d6f162afe883

Thanks & Regards
Ramesh

**Comment by bwsw** [comment]
@ramesh-xinthe `develop` is based on DS7.0, which is known to work with WSL2, and users succeeded in running it. We (as a team) do not test Savant with WSL2.

**Comment by ramesh-xinthe** [comment]
@bwsw 

Sorry my bad its not wsl2.Windows Docker Desktop with integration of WSL2.Could you please help me on this 

I was initiated the "Docker compose" command then the containers are started but i didnt get any output and getting an error as mentioned above screenshots



This is my environment:

Windows 11
Docker Desktop
WSL2 Ubuntu-22.04
NVIDIA GeForce RTX 4060

**Comment by bwsw** [comment]
Hi, as I mentioned earlier and is written in the docs, WSL2 Docker environment (Windows host) is not supported. Try with the ‘develop’ branch which should work.
