### ISSUE TITLE
Make Redis optional in Kafka/Redis sink adapter

### ISSUE THREAD

**Issue by Zardigal** [insight-platform/Savant#889]
Tried to use the Kafka/Redis sink adapter using the template from docker-compose-no-keydb.x86.yml from kafka_redis_adapter sample.

This merge has already tried to fix this problem. 
https://github.com/insight-platform/Savant/pull/521

Redis is still a required.  
On pic 2. When initializing the configs, a check is made to see if there are configs for redis (step 1). Then, when initializing the RedisConfig class, we enter the req_config method on self.host (step 2). Inside, we fall with a ValueError (step 3). We catch KeyError (step 4).

![image](https://github.com/user-attachments/assets/298a8cc8-ad08-467c-9ca2-7cbc3f664726)
![Снимок экрана от 2024-12-04 15-58-16](https://github.com/user-attachments/assets/167d5d3b-6ec2-42c7-bf1d-43eeedfdcaf4)

**Comment by bwsw** [comment]
Hmm. Redis must be optional. 
@tomskikh could you check?

**Comment by tomskikh** [comment]
The problem appeared when config loading was changed from `os.environ['REDIS_HOST']` to `req_config('REDIS_HOST')` - it throws `ValueError`.

**Comment by bwsw** [comment]
@tomskikh, let us do a quick fix. Please backport to `0.4.x`.

**Comment by bwsw** [comment]
@Zardigal we will update develop and create 0.4.9 very soon. Thank you for your input!

**Comment by bwsw** [comment]
@Zardigal when the [action](https://github.com/insight-platform/Savant/actions/runs/12156993070) run is complete you can download 0.4.9 with the fix.
