### ISSUE TITLE
Slow operation `stage/decode`

### ISSUE THREAD

**Issue by nikcleju** [insight-platform/Savant#894]
I'm running a pipeline with YOLOv7 on a RTSP video stream with fairly high resolution (2592x1944). Looking through the Jaeger traces I noticed the `stage/decode` operation takes a lot of time, about 150ms. 

Do you have any idea how can this be improved (besides reducing the resolution, I mean)? Or is it normal to take so much time?

I'm surprised, because I wasn't expecting the decoding to be much slower than the actual inference (8ms) and tracking (33ms), due to HW decoding, even though the resolution is high.

I'm running Savant 0.2.11, the RTSP stream is 2592x1944 @ 20 fps, the GPU should be powerful enough (Tesla V100 32GB).

![image](https://github.com/user-attachments/assets/98756b7b-a52c-4394-a678-2db924c6d64b)

**Comment by bwsw** [comment]
Hi, decoding time does not demonstrate the load and performance because NVDEC buffers 2-3 frames before decoding, so for 20 fps, frame delta is about 50ms, 3 frames buffered give 150 ms.

So, the delay is not because the performance reasons, but because of NVDEC real-time decoding design.

**Comment by nikcleju** [comment]
Thanks for the quick response! 

So, there's basically no way to decrease this latency?

**Comment by bwsw** [comment]
In Savant 0.4 we added low latency decoder:
https://github.com/insight-platform/Savant/pull/855/files

**Comment by bwsw** [comment]
Here is the option: https://github.com/insight-platform/Savant/blob/8ece2dc0a8039334c596b984f84fbfa93e38b577/savant/config/default.yml#L204
