### ISSUE TITLE
Source processing early stop

### ISSUE THREAD

**Issue by abramov-oleg** [insight-platform/Savant#91]
While sending consecutive sources into a module, various problems may be observed.

### Case 1

Input: video source adapter + one video file (50 frames, 60 fps, 1920x1080, h264)
Module: peoplenet_detector
Output: jpeg frames, image-files sink adapter

2nd source's processing stops early, with module completing output of only 1 frame. At the same time 1st source and 3rd and later sources are processed in full, 50 frames written by the sink adapter.

In case sources are started each with their own source-id, sink adapter writes 50 / 1 / 50 frames into their respective directories.
In case sources are started using the same source-id each time, sink adapter similarly writes 50 / 1 / 50 frames into single directory, resulting in cumulative amount of frames of 50 \ 51 \ 101 after 1st, 2nd and 3rd runs respectively.

### Case 2

Input: video source adapter + one video file (1442 frames, 30 fps, 1280x720, h264)
Module: peoplenet_detector
Output: jpeg frames, image-files sink adapter

Sources are started each with their own source-id.
1st source is processed in full, 1442 jpegs written by the sink adapter. 2nd source processing is not finished, module hangs, 1 jpeg written by the sink adapter.

### Case 3

Input: pictures source adapter + one image file (jpeg 1280x720)
Module: peoplenet_detector
Output: jpeg frames, image-files sink adapter

Sources are started each with their own source-id, results OK, as expected.

### Case 4

Input: pictures source adapter + 1400 image files (jpeg 1280x720)
Module: peoplenet_detector
Output: jpeg frames, image-files sink adapter

Sources are started each with their own source-id.
1st source is processed in full, 1400 jpegs written by the sink adapter. 2nd source processing is not finished, module hangs, 1 jpeg written by the sink adapter.

### Case 5

Input: video source adapter + one video file (8340 frames, 60 fps, 1920x1080, h264)
Module: simple, only zmq src + zmq sink
Output: jpeg frames, image-files sink adapter

Source is started 2 times with the same source-id.
Result: 8158 + 1 jpegs written by the sink adapter.

Problem appeared after updating to DS6.2

**Comment by denisvmedyantsev** [comment]
Within the initial task of incomplete processing of all frames, it is necessary to work out the following points (currently it is not easy to reproduce all the original cases)
- [ ] Is there a problem with the processing of one fragment? Test with different fragment lengths, processing speeds, and sources: adapter, uridecodebin.
- [ ] Is there a problem with the simultaneous processing of more than one source? Test with different fragment lengths, and processing speeds.
- [ ] Find understandable and reproducible conditions for the occurrence of the original problem (what and on what to run, how to identify the problem) and describe them

**Comment by denisvmedyantsev** [comment]
1. There is frame loss with the current Dealer-Router configuration for Source-Module. There is no loss if set 1) sync=1 for source (decrease FPS significantly) or 2) modify HWM (requires investigation, see [issue](https://github.com/zeromq/jeromq/issues/703)) or 2) change ZMQ schema to REQ-REP.

**Comment by bwsw** [comment]
When your socket reaches its HWM, it will either block or drop data depending on the socket type. **PUB** and **ROUTER** sockets will drop data if they reach their HWM, while other socket types will block.

**Comment by bwsw** [comment]
Consider changing DEALER/ROUTER to DEALER/DEALER.

**Comment by bwsw** [comment]
https://zguide.zeromq.org/docs/chapter3/#Request-Reply-Combinations

**Comment by bwsw** [comment]
Candidates: 
* DEALER to DEALER;
* DEALER to REP (with replies on processing);

**Comment by denisvmedyantsev** [comment]
3. The problem can be reproduced with the simple pipeline: default source and sink, no elements. There is no problem if we start source adapters one by one without any pause. Launch sources with minimal delay (sleep 0.5) cause only 1 frame processing and hanging of the pipeline for fragments with 1442 and 8340 frames.
I suppose that in the DS 6.2 EOS handling in nvstreammux was updated. There is no any mention of it in the Release notes and we don't have the nvstreammux code, but the new parameter `drop-pipeline-eos` was added to the plugin. Savant pipeline suppresses EOS, but now it's not enough. We can use `drop-pipeline-eos` (set to 1, 0 by default) and should modify our EOS handling.

**Comment by denisvmedyantsev** [comment]
The main issue was resolved in #97
